---
iso3: "KIR"

time:
  start: 1950.
  end: 2020.
  step: 0.1

start_population_size: 33048.
infectious_seed: 0.
crude_death_rate: 1.
age_breakpoints: [0, 5, 15, 35, 50]

age_mixing:
  # type: "prem"
  type: extrapolated
  source_iso3: FJI
  age_adjust: true