---
iso3: "KIR"

age_mixing:
  # type: "prem"
  type: extrapolated
  source_iso3: FJI
  age_adjust: true

time:
  start: 1800.
  end: 2050.
  step: 0.1
  critical_ranges: [[2016., 2020.], [2022., 2025.]]

start_population_size: 2000.

