---
iso3: "KIR"

time:
  start: 1950.
  end: 2020.
  step: 0.1

start_population_size: 33048.
infectious_seed: 1.
crude_death_rate: 1. #time-variant
age_breakpoints: [0, 5, 15, 35, 50]

age_mixing:
  source_iso3: FJI
  age_adjust: true

contact_rate: 0.00178
cumulative_start_time: 1950.