description: BASELINE
parent: apps/covid_19/regions/malaysia/params/default.yml

contact_rate: 0.033

time:
  start: 290

population:
  region: Penang
  year: 2019

mobility:
  microdistancing:
    behaviour:
      parameters:
        upper_asymptote: 0.2
