description: BASELINE
parent: apps/covid_19/regions/malaysia/params/default.yml

contact_rate: 0.027

time:
  start: 280

population:
  region: Penang
  year: 2019

mobility:
  microdistancing:
    behaviour:
      parameters:
        upper_asymptote: 0.2

voc_emergence:
  start_time: 458  # 1 Dec 2020
  entry_rate: 1.
  seed_duration: 10.
  contact_rate_multiplier: 1.56  # LSHTM's estimate