description: BASELINE

country:
  iso3: BEL

ref_mixing_iso3: BEL

mobility:
  mixing:
    school:
      append: false
      times:
        - 2020-03-12
        - 2020-03-13
        - 2020-09-01
        - 2020-09-03
      values:
        - 1.0
        - 0.1
        - 0.1
        - 1.

infectious_seed: 200
contact_rate: 0.04
