---
# Base parameters for the tuberculosis model

# Times to run over
time:
  start: 1800.
  end: 2020.
  step: 0.1

# Country code
iso3: null

# Set up a parameter for the birth rate (its time-variant value will be automatically defined)
crude_birth_rate: 1.
start_population_size: 2000.
infectious_seed: 1.
#stratification
age_breakpoints: [0, 5, 15, 30, 45, 60, 75]
age_mixing: null
custom_stratifications: {} # this specifies user-defined  stratifications, i.e location, will be overwritten later

# basic infection and disease parameters
contact_rate: 1.

# latency parameters
age_specific_latency:
  early_activation:
    # unstratified: 1.1e-3
    0: 6.6e-3
    5: 2.7e-3
    15: 2.7e-4
  stabilisation:
    # unstratified: 1.0e-2
    0: 1.2e-2
    5: 1.2e-2
    15: 5.4e-3
  late_activation:
    # unstratified: 5.5e-6
    0: 1.9e-11
    5: 6.4e-6
    15: 3.3e-6

# Relative risks of reinfection
rr_infection_latent: .21
rr_infection_recovered: 1.
progression_multiplier: 1.

self_recovery_rate_dict:
  unstratified: .2
  smear_positive: 0.231 # Ragonent et al. (CID 2020)
  smear_negative: 0.130 # Ragonent et al. (CID 2020)
# time variant
time_variant_tsr: {}
time_variant_acf: []
acf_screening_sensitivity: .75
time_variant_ltbi_screening: []
time_variant_ltbi_screening: []
ltbi_screening_sensitivity: .75
pt_efficacy: .7


