---
# Base parameters for the tuberculosis model

# Times to run over
time:
  start: 1800.
  end: 2020.
  step: 0.1

# Country code
iso3: null
cumulative_start_time: 1980

# Set up a parameter for the birth rate (its time-variant value will be automatically defined)
crude_birth_rate: 1.
start_population_size: 2000.
infectious_seed: 1.
#stratification
age_breakpoints: [0, 5, 15, 30, 45, 60, 75]
age_mixing: null

# basic infection and disease parameters
contact_rate: 0.0025

# latency parameters
age_specific_latency:
  early_activation:
    # unstratified: 1.1e-3
    0: 6.6e-3
    5: 2.7e-3
    15: 2.7e-4
  stabilisation:
    # unstratified: 1.0e-2
    0: 1.2e-2
    5: 1.2e-2
    15: 5.4e-3
  late_activation:
    # unstratified: 5.5e-6
    0: 1.9e-11
    5: 6.4e-6
    15: 3.3e-6

# relative risks of reinfection
rr_infection_latent: .21
rr_infection_recovered: 1.
progression_multiplier: 1.

self_recovery_rate: .2
infect_death_rate: .2

prop_death_among_negative_tx_outcome: .2
time_variant_tsr: {}
treatment_duration: .5
# infectious changes by age
age_infectiousness_switch: 15.
on_treatment_infect_multiplier: 0.08

time_variant_tb_screening_rate:
  shape: 0.05 # The shape parameter to the tanh-based curve
  inflection_time: 1980. # Point at which curve inflects
  start_asymptote: 0. # Starting value - lower asymptote
  end_asymptote: 10. # End value - upper asymptote

passive_screening_sensitivity: 0.75


