---
# Parameters used to build a general model of sm_covid
description: BASELINE

country:
  iso3: PHL

age_groups:
  - 0
  - 15
  - 25
  - 50
  - 70

ref_mixing_iso3: HKG

population:
  region: null
  year: 2020

time:
  start: 0
  end: 731  # 31 Dec 2021
  step: 1

contact_rate: 0.05
infectious_seed_time: 60
seed_duration: 7

sojourns:
  latent: 3.
  active: 8.

mobility:
  region: null
  mixing:
    school:  # populate the school component to have schools always open when UNESCO data are not being used
      append: False
      times: [0]
      values: [1.]
  age_mixing: null
  # Mapping of Google mobility locations to Prem-specific locations
  google_mobility_locations:
    work:
      workplaces: 1.
    other_locations:
      retail_and_recreation: 0.25
      grocery_and_pharmacy: 0.25
      parks: 0.25
      transit_stations: 0.25
  smooth_google_data: true  # whether to apply a 7-day moving average
  square_mobility_effect: true
  microdistancing: {}
  apply_unesco_school_data: true  # if true, will override school mixing inputs
  unesco_partial_opening_value: .5

# Age-related parameters
age_stratification:
  susceptibility:  # zhang-2020-a, ORs converted to RRs using Tables S14 and S15
    0: 0.36
    5: 0.36
    10: 0.36
    15: 1.
    20: 1.
    25: 1.
    30: 1.
    35: 1.
    40: 1.
    45: 1.
    50: 1.
    55: 1.
    60: 1.
    65: 1.
    70: 1.41
    75: 1.41

  prop_symptomatic:  # sah-2021
    0: 0.533
    5: 0.533
    10: 0.533
    15: 0.533
    20: 0.679
    25: 0.679
    30: 0.679
    35: 0.679
    40: 0.679
    45: 0.679
    50: 0.679
    55: 0.679
    60: 0.803
    65: 0.803
    70: 0.803
    75: 0.803

  prop_hospital:
    values:  #FIXME: These are Delta-related values. Need to update with wild-type values.
      0: 0.0046
      5: 0.0046
      10: 0.0033
      15: 0.0033
      20: 0.0133
      25: 0.0133
      30: 0.0150
      35: 0.0150
      40: 0.0140
      45: 0.0140
      50: 0.0238
      55: 0.0238
      60: 0.0529
      65: 0.0529
      70: 0.1340
      75: 0.1340
      80: 0.2540
    multiplier: 1.

  ifr:
    values:  #FIXME: These are Delta-related values. Need to update with wild-type values. 
      0:  0.00001
      5:  0.00001
      10: 0.00001
      15: 0.00001
      20: 0.00004
      25: 0.00004
      30: 0.0004
      35: 0.0004
      40: 0.0005
      45: 0.0005
      50: 0.0026
      55: 0.0026
      60: 0.0112
      65: 0.0112
      70: 0.0493
      75: 0.0493
      80: 0.159
    multiplier: 1.   

is_dynamic_mixing_matrix: true

# parameters related to immunity stratification (two strata: unvaccinated / vaccinated)
vaccine_effects:
  ve_infection: .5   #FIXME: dummy data 
  ve_hospitalisation: .9  #FIXME: dummy data 
  ve_death: .9  #FIXME: dummy data 

voc_emergence: null

time_from_onset_to_event:  # using time of symptom onset as reference 
  hospitalisation:
    distribution: gamma
    parameters:
      shape: 5.
      mean: 5. # FIXME: need an estimate
  icu_admission:  # using time of hospitalisation as reference
    distribution: gamma
    parameters:
      shape: 5.
      mean: 2. # FIXME: need an estimate
  death:
    distribution: gamma
    parameters:
      shape: 5.
      mean: 14. # FIXME: check

prop_icu_among_hospitalised: .08  # NSW data

hospital_stay:
  hospital_all:
    distribution: gamma
    parameters:
      shape: 5.
      mean: 3. # South Africa data
      
  icu:
    distribution: gamma
    parameters:
      shape: 5.
      mean: 4.7 # NSW data: https://aci.health.nsw.gov.au/__data/assets/pdf_file/0007/698785/20220112-COVID-19-Risk-Monitoring-Dashboard.pdf

activate_random_process: True
random_process: 
  order: 1
  noise_sd: .5
  values: [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]
  time: 
    start: 92  # 1 Apr 2020. Need to make sure this is greater than the seed time to prevent identifiability issues with contact rate
    end: 731  # 31 Dec 2021
    step: 60

requested_cumulative_outputs: ["incidence", "infection_deaths"]
cumulative_start_time: 0.
request_incidence_by_age: False
request_immune_prop_by_age: False