---
# Parameters used to build a general model of sm_sir
description: BASELINE

country:
  iso3: PHL

time:
  start: 0
  end: 365
  step: 1

contact_rate: 0.1
infectious_seed: 1
infection_duration: 8

activate_random_process: True
random_process: null
