---
# Parameters used to build a general model of sm_sir
description: BASELINE

country:
  iso3: PHL

age_groups:
  - 0
  - 15
  - 25
  - 50
  - 70

ref_mixing_iso3: GBR

testing_to_detection: null

population:
  region: null
  year: 2020

time:
  start: 0
  end: 365
  step: 1

contact_rate: 0.1
infectious_seed: 1

detect_prop: 0.5

asympt_infectiousness_effect: 0.5
isolate_infectiousness_effect: 0.2

sojourns:
  latent:
    total_time: 3.
  active:
    total_time: 8.

# Age-related parameters
age_stratification:
  susceptibility:  # zhang-2020-a, ORs converted to RRs using Tables S14 and S15
    0: 0.36
    5: 0.36
    10: 0.36
    15: 1.
    20: 1.
    25: 1.
    30: 1.
    35: 1.
    40: 1.
    45: 1.
    50: 1.
    55: 1.
    60: 1.
    65: 1.
    70: 1.41
    75: 1.41

  prop_symptomatic:  # sah-2021
    0: 0.533
    5: 0.533
    10: 0.533
    15: 0.533
    20: 0.679
    25: 0.679
    30: 0.679
    35: 0.679
    40: 0.679
    45: 0.679
    50: 0.679
    55: 0.679
    60: 0.803
    65: 0.803
    70: 0.803
    75: 0.803

  prop_hospital:
    values:  # Table S2 of nyberg-2022 - Delta values are set as the default, can be over-written with Omicron (see NCR)
      0: 0.0046
      5: 0.0046
      10: 0.0033
      15: 0.0033
      20: 0.0133
      25: 0.0133
      30: 0.0150
      35: 0.0150
      40: 0.0140
      45: 0.0140
      50: 0.0238
      55: 0.0238
      60: 0.0529
      65: 0.0529
      70: 0.1340
      75: 0.1340
      80: 0.2540
    multiplier: 1.
    # Proportions at study mid-point reported 16th December in:
    # https://ourworldindata.org/grapher/share-people-fully-vaccinated-covid?country=~GBR
    # where "none" is complement of those fully vaccinated, and "high" is those boosted by the same date
    source_immunity_distribution:
      none: 0.312
      low: 0.302
      high: 0.386
    # Approximately the values reported in Figure 2 of:
    # https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1054071/
    # vaccine-surveillance-report-week-6.pdf
    # 85% protection once boosted, 50% otherwise
    source_immunity_protection:
      none: 0.
      low: 0.5
      high: 0.85

  cfr:
    values:  # Table S2 of nyberg-2022 - Delta values are set as the default, can be over-written with Omicron (see NCR)
      0:  0.00001
      5:  0.00001
      10: 0.00001
      15: 0.00001
      20: 0.00004
      25: 0.00004
      30: 0.0004
      35: 0.0004
      40: 0.0005
      45: 0.0005
      50: 0.0026
      55: 0.0026
      60: 0.0112
      65: 0.0112
      70: 0.0493
      75: 0.0493
      80: 0.159
    multiplier: 1.
    source_immunity_distribution:  # Same as for hospitalisation
      none: 0.312
      low: 0.302
      high: 0.386
    source_immunity_protection:  # Same as for hospitalisation
      none: 0.
      low: 0.5
      high: 0.85

is_dynamic_mixing_matrix: false

mobility:
  region: null
  mixing: {}
  age_mixing: null
  # Mapping of Google mobility locations to matrix locations
  google_mobility_locations:
    work:
      workplaces: 1.
    other_locations:
      retail_and_recreation: 0.25
      grocery_and_pharmacy: 0.25
      parks: 0.25
      transit_stations: 0.25
  smooth_google_data: false  # whether to apply a 7-day moving average
  square_mobility_effect: true
  microdistancing: {}

# parameters related to immunity stratification (three strata: none / high / low)
immunity_stratification:
  prop_immune: .8
  prop_high_among_immune: .1

  infection_risk_reduction:  # FIXME check source with Dave (that's using the figure showing VE against symptomatic disease)
    none: 0.
    low: 0.
    high: 0.6

time_from_onset_to_event:  # using time of symptom onset as reference
  notification:
    distribution: gamma
    parameters:
      shape: 5.
      mean: 3. # FIXME: need an estimate
  hospitalisation:
    distribution: gamma
    parameters:
      shape: 5.
      mean: 5. # FIXME: need an estimate
  icu_admission:  # using time of hospitalisation as reference
    distribution: gamma
    parameters:
      shape: 5.
      mean: 2. # FIXME: need an estimate
  death:
    distribution: gamma
    parameters:
      shape: 5.
      mean: 14. # FIXME: check

prop_icu_among_hospitalised: .08  # NSW data

hospital_stay:
  hospital_all:
    distribution: gamma
    parameters:
      shape: 5.
      mean: 3. # South Africa data
      
  icu:
    distribution: gamma
    parameters:
      shape: 5.
      mean: 4.7 # NSW data: https://aci.health.nsw.gov.au/__data/assets/pdf_file/0007/698785/20220112-COVID-19-Risk-Monitoring-Dashboard.pdf

activate_random_process: true
random_process: null

additional_immunity: null
booster_effect_duration: 90
future_monthly_booster_rate: null
future_booster_age_allocation: null

indigenous: false

requested_cumulative_outputs: []
cumulative_start_time: null
request_incidence_by_age: false
request_immune_prop_by_age: false
request_hospital_admissions_by_age: false
request_hospital_occupancy_by_age: false
request_icu_admissions_by_age: false
request_icu_occupancy_by_age: false
request_infection_deaths_by_age: false

voc_emergence: null # Emergence of Variants of Concern

vaccine_effects:
  ve_hospitalisation: null
  ve_death: null