description: BASELINE

contact_rate: 0.0215
infectious_seed: 200

time:
  start: 240
  end: 763

country:
  iso3: LKA

contact_tracing:
    assumed_trace_prop: 0.05
    assumed_prev: 1.e-3
    quarantine_infect_multiplier: 0.2


vaccination:
  roll_out_components:
    - supply_period_coverage:
        coverage: 0.12
        start_time: 481 # 25 Apr 2021
        end_time: 586 # 08 August 2021
    - supply_period_coverage:
        coverage: 0.38
        start_time: 587 # 09 August 2021
        end_time: 609 # 31 August 2021
    - supply_period_coverage:
        coverage: 0.30
        start_time: 610 #01  September 2021
        end_time: 732 # 1 Jan 2022


testing_to_detection:
  assumed_tests_parameter: 1.e-04
  assumed_cdr_parameter: 0.06
  smoothing_period: 14

clinical_stratification:
  icu_prop: 0.04

mobility:
  microdistancing:
    behaviour:
      function_type: tanh
      parameters:
        shape: .02
        inflection_time: 380. # 1st February 2021
        lower_asymptote: 0.
        upper_asymptote: 0.4
      locations:
        - other_locations
        - school
        - work
        - home
  mixing:
    school:
      append: false
      times:
        - 2020-03-13 # All schools close
        - 2020-03-14
        - 2020-07-06 # schools partial re-open
        - 2020-07-07
        - 2020-07-12 # Full schools close again
        - 2020-07-13
        - 2020-07-27 # Schools partial reopen
        - 2020-07-28
        - 2020-08-10 # Schools fully open again
        - 2020-08-11
        - 2020-11-03 # Schools fully close again
        - 2020-11-04
        - 2020-12-14 # All but western province re-open
        - 2020-12-15
        - 2021-01-11 # All but high isolated schools re-open
        - 2021-01-12
        - 2021-05-05 # All schools close
        - 2021-05-06
      values:
        - 1.
        - 0.
        - 0.
        - 0.2
        - 0.2
        - 0
        - 0
        - 0.5
        - 0.5
        - 1
        - 1
        - 0.
        - 0.
        - 0.5
        - 0.5
        - 1
        - 1
        - 0
    other_locations:
      append: true
      times:
        - 2021-08-20
        - 2021-08-21
        - 2021-08-22
      values:
        - - repeat_prev
        - 0.6
        - 0.3
    work:
      append: true
      times:
        - 2021-08-20
        - 2021-08-21
        - 2021-08-22
      values:
        - - repeat_prev
        - 0.6
        - 0.3

voc_emergence:
  alpha_beta:
    start_time: 410
    entry_rate: 1.
    seed_duration: 10.
    contact_rate_multiplier: 1.3 # LSHTM's estimate
  delta:
    start_time: 548 # July 01
    entry_rate: 1.
    seed_duration: 10.
    contact_rate_multiplier: 2.2

waning_immunity_duration: 365
