description: BASELINE

contact_rate: 0.0215
infectious_seed: 200

time:
  start: 200
  end: 913 # July 1st 2022

country:
  iso3: LKA

mixing_matrices:
  source_iso3: CHN

contact_tracing:
  assumed_trace_prop: 0.896
  assumed_prev: 1.e-3
  quarantine_infect_multiplier: 0.2
  floor: 0.

vaccination:
  one_dose:
    ve_sympt_covid: 0.3
    ve_prop_prevent_infection: 0.8
    ve_infectiousness_ratio: 0.5
    ve_hospitalisation: 0.7
    ve_death: 0.8
  fully_vaccinated:
    ve_sympt_covid: 0.5
    ve_prop_prevent_infection: 0.8
    ve_infectiousness: 0.3
    ve_hospitalisation: 0.7
    ve_death: 0.8
  part_waned:
    ve_sympt_covid: 0.25
    ve_prop_prevent_infection: 0.8
    ve_infectiousness: 0.15
    ve_hospitalisation: 0.7
    ve_death: 0.8
  fully_waned:
    ve_sympt_covid: 0.
    ve_prop_prevent_infection: 0.
    ve_infectiousness: 0.
    ve_hospitalisation: 0.35
    ve_death: 0.4
  standard_supply: false # to get the timeseries of vaccine coverage
  lag: 14
  second_dose_delay: 30.
  vacc_full_effect_duration: 90.
  vacc_part_effect_duration: 360.
  roll_out_components:
    - age_min: 15
      supply_period_coverage:
        coverage: 0.7587 # 58% total population coverage by Oct 15
        start_time: 481 # 25 April 2021
        end_time: 654 # 15 Oct 2021
    - age_min: 15
      supply_period_coverage:
        coverage: 0.18 #80% coverage by Jan 1 among 15+ age_group
        start_time: 655 #16  Oct 2021
        end_time: 732 # 1 Jan 2022


testing_to_detection:
  assumed_tests_parameter: 1.e-04
  assumed_cdr_parameter: 0.06
  smoothing_period: 14

clinical_stratification:
  icu_prop: 0.04
  props:
    symptomatic:
      multiplier: 0.076

mobility:
  smooth_google_data: false # whether to apply a 7-day moving average
  square_mobility_effect: true
  google_mobility_locations:
    work:
      workplaces: 1.
    other_locations:
      retail_and_recreation: 0.3334
      grocery_and_pharmacy: 0.3333
      transit_stations: 0.3333
      parks: 0.
    home:
      residential: 1.
  microdistancing:
    behaviour:
      function_type: tanh
      parameters:
        shape: .02
        inflection_time: 380. # 1st February 2021
        start_asymptote: 0.
        end_asymptote: 0.4
      locations:
        - other_locations
        - school
        - work
        - home
  mixing:
    school:
      append: false
      times:
        - 2020-03-13 # All schools close
        - 2020-03-14
        - 2020-07-06 # schools partial re-open
        - 2020-07-07
        - 2020-07-12 # Full schools close again
        - 2020-07-13
        - 2020-07-27 # Schools partial reopen
        - 2020-07-28
        - 2020-08-10 # Schools fully open again
        - 2020-08-11
        - 2020-11-03 # Schools fully close again
        - 2020-11-04
        - 2020-12-14 # All but western province re-open
        - 2020-12-15
        - 2021-01-11 # All but high isolated schools re-open
        - 2021-01-12
        - 2021-05-05 # All schools close
        - 2021-05-06
        - 2021-11-21
        - 2021-11-22 # All schools open
      values:
        - 1.
        - 0.
        - 0.
        - 0.2
        - 0.2
        - 0
        - 0
        - 0.5
        - 0.5
        - 1
        - 1
        - 0.
        - 0.
        - 0.5
        - 0.5
        - 1
        - 1
        - 0
        - 0
        - 1

voc_emergence:
  alpha_beta:
    start_time: 410
    entry_rate: 400.
    seed_duration: 10.
    contact_rate_multiplier: 1.3 # LSHTM's estimate
    ifr_multiplier: 1.
    hosp_multiplier: 2.38
  delta:
    start_time: 548 # July 01
    entry_rate: 400.
    seed_duration: 10.
    contact_rate_multiplier: 2.2
    ifr_multiplier: 3.5
    hosp_multiplier: 2.08
  omicron:
    start_time: 2000 # July 01
    entry_rate: 400.
    seed_duration: 10.
    contact_rate_multiplier: 15
    ifr_multiplier: 3.5
    hosp_multiplier: 2.08

history:
  experienced:
    ve_sympt_covid: 0.94
    ve_prop_prevent_infection: 0.85
    ve_infectiousness_ratio: 0.3
    ve_hospitalisation: 0.95
    ve_death: 0.95
  waned:
    ve_sympt_covid: 0.28
    ve_prop_prevent_infection: 0.8
    ve_infectiousness: 0.15
    ve_hospitalisation: 0.5
    ve_death: 0.5
  natural_immunity_duration: 285.

sojourn:
  compartment_periods_calculated:
    exposed:
      total_period: 6.16
    active:
      total_period: 6.53