description: BASELINE

contact_rate: 0.0215
infectious_seed: 445

time:
  start: 250
  end: 791 # 913 July 1st 2022

country:
  iso3: LKA

mixing_matrices:
  source_iso3: CHN

contact_tracing: #Proportion of contacts of identified cases detected at a prevalence of one active case per thousand population.
  assumed_trace_prop: 0.76
  assumed_prev: 1.e-3
  quarantine_infect_multiplier: 0.2
  floor: 0.

vaccination:
  one_dose:
    ve_sympt_covid: 0.3
    ve_prop_prevent_infection: 0.8
    ve_infectiousness_ratio: 0.5
    ve_hospitalisation: 0.6
    ve_death: 0.8
  fully_vaccinated:
    ve_sympt_covid: 0.68
    ve_prop_prevent_infection: 0.85
    ve_infectiousness: 0.3
    ve_hospitalisation: 0.8
    ve_death: 0.85
  part_waned:
    ve_sympt_covid: 0.5
    ve_prop_prevent_infection: 0.7
    ve_infectiousness: 0.15
    ve_hospitalisation: 0.55
    ve_death: 0.75
  fully_waned:
    ve_sympt_covid: 0.
    ve_prop_prevent_infection: 0.
    ve_infectiousness: 0.
    ve_hospitalisation: 0.
    ve_death: 0.65
  standard_supply: true # to get the timeseries of vaccine coverage
  lag: 14
  second_dose_delay: 30.
  vacc_full_effect_duration: 90.
  vacc_part_effect_duration: 360.

testing_to_detection:
  assumed_tests_parameter: 1.e-04
  assumed_cdr_parameter: 0.017
  smoothing_period: 14

clinical_stratification:
  icu_prop: 0.08
  props:
    symptomatic:
      multiplier: 1.0

mobility:
  smooth_google_data: false # whether to apply a 7-day moving average
  square_mobility_effect: true
  google_mobility_locations:
    work:
      workplaces: 1.
    other_locations:
      retail_and_recreation: 0.3334
      grocery_and_pharmacy: 0.3333
      transit_stations: 0.3333
      parks: 0.
    home:
      residential: 1.
  microdistancing:
    behaviour:
      function_type: tanh
      parameters:
        shape: .02
        inflection_time: 380. # 1st February 2021
        start_asymptote: 0.
        end_asymptote: 0.4
      locations:
        - other_locations
        - school
        - work
        - home
  mixing:
    school:
      append: false
      times:
        - 2020-03-13 # All schools close
        - 2020-03-14
        - 2020-07-06 # schools partial re-open
        - 2020-07-07
        - 2020-07-12 # Full schools close again
        - 2020-07-13
        - 2020-07-27 # Schools partial reopen
        - 2020-07-28
        - 2020-08-10 # Schools fully open again
        - 2020-08-11
        - 2020-11-03 # Schools fully close again
        - 2020-11-04
        - 2020-12-14 # All but western province re-open
        - 2020-12-15
        - 2021-01-11 # All but high isolated schools re-open
        - 2021-01-12
        - 2021-05-05 # All schools close
        - 2021-05-06
        - 2021-11-21
        - 2021-11-22 # All schools open
      values:
        - 1.
        - 0.
        - 0.
        - 0.2
        - 0.2
        - 0
        - 0
        - 0.5
        - 0.5
        - 1
        - 1
        - 0.
        - 0.
        - 0.5
        - 0.5
        - 1
        - 1
        - 0
        - 0
        - 1

voc_emergence:
  alpha_beta:
    start_time: 417
    entry_rate: 25.
    seed_duration: 10.
    contact_rate_multiplier: 1.3 # LSHTM's estimate
    ifr_multiplier: 1.51
    hosp_multiplier: 1.52
  delta:
    start_time: 517 #
    entry_rate: 25.
    seed_duration: 10.
    contact_rate_multiplier: 2.2
    ifr_multiplier: 2.33
    hosp_multiplier: 2.08

history:
  experienced:
    ve_sympt_covid: 0.9
    ve_prop_prevent_infection: 0.85
    ve_infectiousness_ratio: 0.3
    ve_hospitalisation: 0.95
    ve_death: 0.95
  waned:
    ve_sympt_covid: 0.28
    ve_prop_prevent_infection: 0.8
    ve_infectiousness: 0.15
    ve_hospitalisation: 0.5
    ve_death: 0.8
  natural_immunity_duration: 425.

sojourn:
  compartment_periods_calculated:
    exposed:
      total_period: 3.16
    active:
      total_period: 3.13

notifications_dispersion_param: 538.601128345239
infection_deaths_dispersion_param: 26.54605666170518

hospital_reporting: 0.5