---
parent: null
# Base parameters for the sir_example model.

# Parameters used to build a general model of COVID-19 disease for application to Australia or internationally
start_time: 0.
end_time: 100.
time_step: 1

contact_rate: 0.3
recovery_rate: 1.0
