---
iso3: "PHL"

# FIXME: These numbers are made up to prevent the region model from crashing.
time_variant_tsr: # should always be > 0
  1995: 0.5
  2017.: 0.5

calculated_outputs:
  [
    "prevalence_infectious",
    "percentage_latent",
    "population_size",
    "notifications",
    "mortality",
    "incidence",
  ]
