description: BASELINE

time:
  start: 480 # 29th Apr 2021
  end: 912

country:
  iso3: VNM

mixing_matrices:
  source_iso3: HKG

# mixing_matrices:
  # type: extrapolated
  # source_iso3: HKG

population:
  region: Hanoi
  year: 2019

mobility:
  region: Hanoi
  # Google mobility data
  smooth_google_data: true # whether to apply a 7-day moving average
  square_mobility_effect: true
  # Google mobility weightings
  google_mobility_locations:
    work:
      workplaces: 1.
    other_locations:
      retail_and_recreation: 0.4
      grocery_and_pharmacy: 0.3
      parks: 0.2
      transit_stations: 0.1
  # Micro distancing
  microdistancing:
    behaviour:
      function_type: empiric
      parameters:
        max_effect: .2 # estimated from the Philipines paper
        times:
          - 485 # 29th April 2021, first community case of COVID-19 detected in Ho Chi Minh City
          - 505 # 19th May 2021, two new cases first detected after 20 days without any new case
          - 518 # 01st Jun 2021, social distancing city-wide under Directive No. 15 of the PM, with Directive No.16 in place at Go Vap District
          - 546 # 29th Jun 2021, Directive No.10 of HCMC's authorities in place
          - 556 # 09th Jul 2021, Directive No.16 of the PM in place city-wide
          - 573 # 26th Jul 2021, curfew from 6PM to 6AM
          - 601 # 23th Aug 2021, total lockdown implemented
          - 640 # 01st Oct 2021, lockdown started to ease
        values:
          - 0
          - 0.2
          - 0.4
          - 0.5
          - 0.7
          - 0.85
          - 1.
          - 0.8
      locations:
        - other_locations
        - school
        - work
        - home
  mixing:
    school:
      append: false
      times:
        - 2021-05-09 # All schools switched to online learning, school year 2020-2021 ended
        - 2021-10-20 # Multiple universities started to allow students to come back to finish the degree. Source: Tuoitre.
      values:
        - 0.
        - 0.1

voc_emergence:
  omicron:
    start_time: 2000.
    entry_rate: 1.
    seed_duration: 10.
    contact_rate_multiplier: 5.
    ifr_multiplier: 1.

sojourn:
  compartment_periods:
    hospital_late: 8.0
    icu_early: 10.0 # 7.7 + 2.3
    icu_late: 18.9 # Source: https://bmcinfectdis.biomedcentral.com/articles/10.1186/s12879-021-06371-6

testing_to_detection:
  assumed_tests_parameter: 1e-04 # Sri-Lanka model
  assumed_cdr_parameter: 0.05 # needs calibrating
  smoothing_period: 14


# Vaccination-related
# All information provided here are HISTORICAL. Last update: 15th Jan, 2022.
# All figures calculated below are available at: https://bit.ly/Hanoi_vaccination_status
# To illustrate the vaccination for under 18, we illustrate the population in three parts: over 20, 15 - 20, and under 15
# Before 15/11, only individuals over 18 are fully vaccinated.
vaccination:
  one_dose:
    ve_sympt_covid: 0.5226
    ve_prop_prevent_infection: 0.9 # one dose AZ has a quite lower efficacy towards infection
    ve_infectiousness_ratio: 0.3292 # 0.0931 / 0.2828
    ve_hospitalisation: 0.8249
    ve_death: 0.9043
  fully_vaccinated:
    ve_sympt_covid: 0.6616 # weighted average
    ve_prop_prevent_infection: 0.95 # high proportion with all types of vaccines
    ve_infectiousness: 0.2828
    ve_hospitalisation: 0.8993 # weighted average
    ve_death: 0.9138 # weighted average
  part_waned:
    ve_sympt_covid: 0.4984
    ve_prop_prevent_infection: 0.95 # high proportion with all types of vaccines
    ve_infectiousness: 0.2348
    ve_hospitalisation: 0.7600
    ve_death: 0.7793
  fully_waned:
    ve_sympt_covid: 0.00
    ve_prop_prevent_infection: 0.00
    ve_infectiousness: 0.00
    ve_hospitalisation: 0.5 # Myanmar
    ve_death: 0.5 # Myanmar
  boosted:
    ve_sympt_covid: 0.8
    ve_prop_prevent_infection: 0.95
    ve_infectiousness: 0.4
    ve_hospitalisation: 0.95
    ve_death: 0.95
  lag: 14
  standard_supply: false
  second_dose_delay:  32.67 # weighted average waiting time between two doses
  boost_delay: 2000. # Equivalent to no vaccination booster
  vacc_full_effect_duration: 90. # 3 months
  vacc_part_effect_duration: 180. # 6 months
  roll_out_components: # --> stratify by time
    - age_min: 20
      supply_period_coverage:
        coverage: .001235
        start_time: 485 # 29th April 2021
        end_time: 518 # 01st June 2021
    - age_min: 20
      supply_period_coverage:
        coverage: .006387
        start_time: 518 # 01st June 2021
        end_time: 545 # 28th June 2021
    - age_min: 20
      supply_period_coverage:
        coverage: 0.001301
        start_time: 545 # 28th June 2021
        end_time: 556 # 09th July 2021
    - age_min: 20
      supply_period_coverage:
        coverage: 0.001932
        start_time: 556 # 09th July 2021
        end_time: 572 # 25th July 2021
    - age_min: 20
      supply_period_coverage:
        coverage: 0.0288
        start_time: 572 # 25th July 2021
        end_time: 593 # 15th Aug 2021
    - age_min: 20
      supply_period_coverage:
        coverage: 0.0388
        start_time: 593 # 15th Aug 2021
        end_time: 610 # 01st Sep 2021
    - age_min: 20
      supply_period_coverage:
        coverage: 0.1976
        start_time: 610 # 01st Sep 2021
        end_time: 624 # 15th Sep 2021
    - age_min: 20
      supply_period_coverage:
        coverage: 0.2965
        start_time: 624 # 15th Sep 2021
        end_time: 640 # 01st Oct 2021
    - supply_period_coverage:
        coverage: 0.000366
        start_time: 485 # 29th Apr 2021
        end_time: 518 # 01st Jun 2021
      age_min: 15
      age_max: 19
    - supply_period_coverage:
        coverage: 0.00189
        start_time: 518 # 01st Jun 2021
        end_time: 545 # 28th Jun 2021
      age_min: 15
      age_max: 19
    - supply_period_coverage:
        coverage: 0.000383
        start_time: 545 # 28th Jun 2021
        end_time: 556 # 09th Jul 2021
      age_min: 15
      age_max: 19
    - supply_period_coverage:
        coverage: 0.000568
        start_time: 556 # 09th Jul 2021
        end_time: 572 # 25th Jul 2021
      age_min: 15
      age_max: 19
    - supply_period_coverage:
        coverage: 0.00846
        start_time: 572 # 25th Jul 2021
        end_time: 593 # 15th Aug 2021
      age_min: 15
      age_max: 19
    - supply_period_coverage:
        coverage: 0.011185
        start_time: 593 # 15th Aug 2021
        end_time: 610 # 01st Sep 2021
      age_min: 15
      age_max: 19
    - supply_period_coverage:
        coverage: 0.05534
        start_time: 610 # 01st Sep 2021
        end_time: 624 # 15th Sep 2021
      age_min: 15
      age_max: 19
    - supply_period_coverage:
        coverage: 0.070507
        start_time: 624 # 15th Sep 2021
        end_time: 640 # 01st Oct 2021
      age_min: 15
      age_max: 19
    - age_min: 20
      supply_period_coverage:
        coverage: 0.2485
        start_time: 640 # 01st Oct 2021
        end_time: 654 # 15th Oct 2021
    - age_min: 20
      supply_period_coverage:
        coverage: 0.0616
        start_time: 654 # 15th Oct 2021
        end_time: 670 # 31st Oct 2021
    - age_min: 20
      supply_period_coverage:
        coverage: 0.0470
        start_time: 670 # 31st Oct 2021
        end_time: 685 # 15th Nov 2021
    - supply_period_coverage:
        coverage: 0.044739
        start_time: 640 # 01st Oct 2021
        end_time: 654 # 15th Oct 2021
      age_min: 15
      age_max: 19
    - supply_period_coverage:
        coverage: 0.008727
        start_time: 654 # 15th Oct 2021
        end_time: 670 # 31st Oct 2021
      age_min: 15
      age_max: 19
    - supply_period_coverage:
        coverage: 0.006306
        start_time: 670 # 31st Oct 2021
        end_time: 685 # 15th Nov 2021
      age_min: 15
      age_max: 19