iso3: GBR

#start_time: -20.
end_time: 180.

infectious_seed: 200
use_verity_mortality_estimates: False

# MLE estimates
contact_rate: 0.0463121996697136
start_time: 14.590114648689246
npi_effectiveness:
  other_locations: 0.5339190164516376
compartment_periods_calculated:
  incubation:
    total_period: 3.326291748191936
  total_infectious:
    total_period: 4.681127858790497
tv_detection_b: 0.07743204852476339
tv_detection_c: 92.29047209008272
prop_detected_among_symptomatic: 0.990438520098133
icu_prop: 0.19434108848653572
ifr_double_exp_model_params:
  k: 7.237845734202136
  last_representative_age: 82.41761813816076

mixing:
  school:
    append: false
    times:
      - 78
      - 80
      - 171
    values:
      - 1.0
      - 0.1
      - 0.1

# Mapping of Google Mobility locations to Autumn-specific locations
google_mobility_locations:
  work:
    - workplaces
  other_locations:
    # Parks not included
    - retail_and_recreation
    - grocery_and_pharmacy
    - transit_stations
