description: BASELINE
parent: apps/covid_19/phl_submodel_params.yml

population:
  region: Calabarzon

mobility:
  region: Calabarzon
  microdistancing:
    behaviour:
      parameters:
        times:
        - 75  # copy default values
        - 314  # copy default values
        - 446  # 21/3
        - 447  # 22/3 GCQ+ starts
        - 467  # 28/3 GCQ+ ends
        - 472  # 29/3 MECQ starts
        - 486  # MECQ ends
        - 490  # back to pre-ECQ MHS
        values:
        - 0.
        - 1.
        - 1.0
        - 1.3
        - 1.3
        - 2.
        - 2.
        - 1.3
  mixing:
    other_locations:
      append: true
      times:
      - 2021-04-11 # GCQ ends
      - 2021-04-13 # MECQ starts
      - 2021-04-30 # MECQ ends
      - 2021-05-02 # back to pre-ECQ mobility
      values:
      - ["repeat_prev"]  # ECQ ends
      - 0.4  # MECQ mobility based on Aug 4-18 2020
      - 0.4
      - 0.55
    work:
      append: true
      times:
      - 2021-04-11 # GCQ ends
      - 2021-04-13 # MECQ starts
      - 2021-04-30 # MECQ ends
      - 2021-05-02 # back to pre-ECQ mobility
      values:
      - ["repeat_prev"]  # ECQ ends
      - 0.4  # MECQ Work mobility based on Aug 4-18 2020
      - 0.4
      - 0.6 # back to pre-ECQ mobility
