description: BASELINE
parent: apps/covid_19/phl_submodel_params.yml

population:
  region: Calabarzon

mobility:
  region: Calabarzon
  mixing:
    school:
      append: false
      times:
        - 2020-02-11
        - 2020-03-16
      values:
        - 1.
        - 0.
