description: BASELINE
parent: apps/covid_19/phl_submodel_params.yml

population:
  region: Central Visayas

mobility:
  region: Central Visayas
  mixing:
    school:
      append: false
      times:
        - 2020-02-11
        - 2020-03-16
      values:
        - 1.
        - 0.

voc_emmergence:
  final_proportion: 0.5
  start_time: 336  # 1 Dec 2020
  end_time: 397  # 31 Jan 2021
  contact_rate_multiplier: 1.56  # LSHTM's estimate
