description: BASELINE

country:
  iso3: GBR

ref_mixing_iso3: GBR

mobility:
  mixing:
    school:
      append: false
      times:
        - 2020-03-18
        - 2020-03-20
        - 2020-09-01
        - 2020-09-03
      values:
        - 1.0
        - 0.1
        - 0.1
        - 1.0

infectious_seed: 400
contact_rate: 0.055
