---
parent: apps/tuberculosis/params.yml
iso3: "MHL"
start_time: 1800.
end_time: 2020.
time_step: 1.
start_population_size: 1150

# MODEL STRUCTURE
stratify_by: ['age', 'location']  #  ['location', 'age', 'organ']
age_breakpoints: [0, 5, 15, 35, 50]
user_defined_stratifications:  # this specifies user-defined  stratifications
  location:
    strata: ['majuro', 'ebeye', 'other']
    proportions:
      majuro: .523
      ebeye: .2
      other: .277
    mixing_matrix:
      - [0.9, 0.05, 0.05]
      - [0.05, 0.9, 0.05]
      - [0.05, 0.05, 0.9]
    adjustments:
      contact_rate:
        majuro: 1.
        ebeye: 1.
        other: 1.
      detection_rate:
        majuro: 1.
        ebeye: 1.6786000040607503
        other: 0.5018196675663678

# BCG coverage
time_variant_bcg_perc:
  1930: 0.
  1990: 49.
  1991: 71.
  1992: 72.
  1993: 88.
  1994: 96.
  1995: 71.
  1996: 98.
  1997: 94.
  1998: 81.
  1999: 81.
  2000: 89.
  2001: 99.
  2002: 90.
  2003: 93.
  2004: 91.
  2005: 93.
  2006: 92.
  2007: 92.
  2008: 95.
  2009: 98.
  2010: 99.
  2011: 80.
  2012: 97.
  2013: 93.
  2014: 89.
  2015: 99.
  2016: 94.
  2017: 92.
  2018: 98.
  2019: 89.

time_variant_tsr:  # should always be > 0
  1950: .6
  2017.: 0.87

time_variant_tb_screening_rate:
  maximum_gradient: .05 # The shape parameter to the tanh-based curve
  max_change_time: 1980. # Point at which curve inflects
  start_value: 0. # Starting value - lower asymptote
  end_value: 0.13309195366287707

extra_params:
  prop_diabetes:
    0: 0.01
    5: 0.05
    15: 0.2
    35: 0.4
    50: 0.7
    70: 0.7
  rr_progression_diabetes: 3.3729636822007314

# calibrated parameters
age_specific_latency:
  early_activation_rate:
    age_0: 0.005391540407789577
    age_15: 0.00033039704280804255
    age_5: 0.001843487341854491
  late_activation_rate:
    age_0: 9.430694060050837e-06
    age_15: 6.379176392561021e-06
    age_5: 1.4724001036290526e-05

contact_rate: 0.41043122702821716


# REQUESTED OUTPUTS
calculated_outputs: ['prevalence_infectious', 'percentage_latent', 'population_size', 'notifications', 'mortality', 'incidence']
outputs_stratification:
  prevalence_infectious: ['location']
  percentage_latent: ['location']
  notifications: ['location']


inflate_reactivation_for_diabetes: True

