---
parent: apps/tuberculosis/params.yml
iso3: "MHL"

time:
  start: 1800.
  end: 2050.
  step: 1.
  critical_ranges: [[2017., 2019.]]

start_population_size: 2000.

# MODEL STRUCTURE
stratify_by: ["age", "organ", "location"]
age_breakpoints: [0, 5, 15, 35, 50]
user_defined_stratifications: # this specifies user-defined  stratifications
  location:
    strata: ["majuro", "ebeye", "other"]
    proportions:
      majuro: .523
      ebeye: .2
      other: .277
    mixing_matrix:
      - [0.95, 0.025, 0.025]
      - [0.025, 0.95, 0.025]
      - [0.025, 0.025, 0.95]
    adjustments:
      contact_rate:
        majuro: 1.
        ebeye: 1.
        other: 1.
      detection_rate:
        majuro: 1.
        ebeye: 1.495354866232787
        other: 1.2325688858220845

# BCG coverage
time_variant_bcg_perc:
  1930: 0.
  1990: 49.
  1991: 71.
  1992: 72.
  1993: 88.
  1994: 96.
  1995: 71.
  1996: 98.
  1997: 94.
  1998: 81.
  1999: 81.
  2000: 89.
  2001: 99.
  2002: 90.
  2003: 93.
  2004: 91.
  2005: 93.
  2006: 92.
  2007: 92.
  2008: 95.
  2009: 98.
  2010: 99.
  2011: 80.
  2012: 97.
  2013: 93.
  2014: 89.
  2015: 99.
  2016: 94.
  2017: 92.
  2018: 98.
  2019: 89.

time_variant_tsr: # should always be > 0
  1995: .25
  2017.: 0.8

time_variant_tb_screening_rate:
  maximum_gradient: .1 # The shape parameter to the tanh-based curve
  max_change_time: 1990. # Point at which curve inflects
  start_value: 0. # Starting value - lower asymptote
  end_value: 0.4057634920539735

extra_params:
  prop_diabetes:
    0: 0.01
    5: 0.05
    15: 0.2
    35: 0.4
    50: 0.7
  rr_progression_diabetes: 5.643402828077587
  future_diabetes_multiplier: 1.

# calibrated parameters
contact_rate: 1.5
progression_multiplier: 0.7117191601170418

# REQUESTED OUTPUTS
calculated_outputs:
  [
    "prevalence_infectious",
    "percentage_latent",
    "population_size",
    "notifications",
    "mortality",
    "incidence",
    "cumulative_diseased",
    "cumulative_deaths"
  ]
outputs_stratification:
  prevalence_infectious: ["location"]
  percentage_latent: ["location"]
  notifications: ["location"]
  incidence: ["location"]
  mortality: ["location"]

cumulative_output_start_time: 2018.

inflate_reactivation_for_diabetes: True


# Implement past interventions
time_variant_acf:
  - stratum_filter: { "location": "ebeye" }
    time_variant_screening_rate:
      2017: 0.
      2017.01: 3.79
      2017.5: 3.79
      2017.51: 0.
    exclude_age: [0, 5]
  - stratum_filter: { "location": "majuro" }
    time_variant_screening_rate:
      2018: 0.
      2018.01: 3.22
      2018.5: 3.22
      2018.51: 0.

time_variant_ltbi_screening:
  - stratum_filter: { "location": "majuro" }
    time_variant_screening_rate:
      2018: 0.
      2018.01: 3.22
      2018.5: 3.22
      2018.51: 0.


awareness_raising:
  relative_screening_rate: 1.25
  scale_up_range: [2018, 2019]

hh_contacts_pt:
  start_time: 2020
  prop_smearpos_among_prev_tb: .40
  prop_hh_transmission: .30
  prop_hh_contacts_screened: .70
  prop_pt_completion: .5
