description: BASELINE

country:
  iso3: MMR

mixing_matrices:
  source_iso3: CHN

time:
  start: 330.
  end: 883.

infectious_seed: 100.  # Ignore, calibrated

contact_rate: 0.04  # Ignore, calibrated

stratify_by_infection_history: true
waning_immunity_duration: 365.  # Ignore, calibrated

testing_to_detection:
  assumed_tests_parameter: 1.e-04
  assumed_cdr_parameter: 0.02  # Ignore, calibrated
  smoothing_period: 7

sojourn:
  compartment_periods:
    hospital_early: 7.
    hospital_late: 7.
    icu_early: 7.
    icu_late: 7.

vaccination:
  one_dose:
    ve_sympt_covid: 0.3
    ve_prop_prevent_infection: 0.8
    ve_infectiousness_ratio: 0.5
    ve_hospitalisation: 0.7
    ve_death: 0.8
  fully_vaccinated:
    ve_sympt_covid: 0.5
    ve_prop_prevent_infection: 0.8
    ve_infectiousness: 0.3
    ve_hospitalisation: 0.7
    ve_death: 0.8
  lag: 14
  second_dose_delay: 50.
  roll_out_components:
    - age_min: 10
      supply_period_coverage:
        coverage: 0.3
        start_time: 487  # Start May 2021
        end_time: 731  # End 2021
