description: BASELINE

country:
  iso3: MMR

mixing_matrices:
  source_iso3: CHN

time:
  start: 198
  end: 1096

mobility:
  microdistancing:
    behaviour:
      function_type: tanh
      parameters:
        shape: 0.04
        inflection_time: 285.
        start_asymptote: 0.
        end_asymptote: 0.22  # Will be calibrated
      locations:
        - other_locations
        - school
        - work
        - home

waning_immunity_duration: 365.

voc_emergence:
  delta:
    start_time: 365.
    entry_rate: 1.
    seed_duration: 10.
    contact_rate_multiplier: 1.85  # Will be calibrated

testing_to_detection:
  assumed_tests_parameter: 1.e-04
  assumed_cdr_parameter: 0.02  # Ignore, calibrated
  smoothing_period: 7

sojourn:
  compartment_periods:
    hospital_early: 7.
    hospital_late: 7.
    icu_early: 7.
    icu_late: 10.

vaccination:
  one_dose:
    ve_sympt_covid: 0.28
    ve_prop_prevent_infection: 0.8
    ve_infectiousness_ratio: 0.5
    ve_hospitalisation: 0.42
    ve_death: 0.42
  fully_vaccinated:
    ve_sympt_covid: 0.56
    ve_prop_prevent_infection: 0.8
    ve_infectiousness: 0.3
    ve_hospitalisation: 0.84
    ve_death: 0.84
  part_waned:
    ve_sympt_covid: 0.28
    ve_prop_prevent_infection: 0.8
    ve_infectiousness: 0.15
    ve_hospitalisation: 0.84
    ve_death: 0.84
  waned:
    ve_sympt_covid: 0.
    ve_prop_prevent_infection: 0.
    ve_infectiousness: 0.
    ve_hospitalisation: 0.5
    ve_death: 0.5
  lag: 14
  standard_supply: true
  second_dose_delay: 60.
  vacc_full_effect_duration: 90.
  vacc_part_effect_duration: 360.
