description: BASELINE

contact_rate: 1.5

time:
  start: 500
  end: 791 # march 1st 2022

country:
  iso3: MMR

mixing_matrices:
  source_iso3: CHN

# PLEASE REVIEW THIS  
testing_to_detection:
  assumed_tests_parameter: 1.e-04
  assumed_cdr_parameter: 0.06
  smoothing_period: 14