---
# Parameters used to build a general model of COVID-19 disease
parent: null

seasonal_force: null
waning_immunity_duration: null
# Compulsory parameter that is completely overwritten in stratification, rather than being modified
infect_death: 0.
# Compulsory parameter for all models, even though there are no population-wide deaths
universal_death_rate: 0.
infectious_seed: 10 # Initial condition
contact_rate: 0.03 # Routinely calibrated, see respective calibration files

time:
  start: 40.
  end: 550.
  step: 1.

country:
  iso3: null

population:
  region: null
  year: 2020

age_stratification:
  max_age: 80
  age_step_size: 5
  # Age-based susceptibility from LSHTM, used mean values
  susceptibility:
    "0": 0.40 # 0-4
    "5": 0.40 # 5-9
    "10": 0.38 # 10-14
    "15": 0.38 # 15-19
    "20": 0.79 # 20-24
    "25": 0.79 # 25-29
    "30": 0.86 # 30-34
    "35": 0.86 # 35-39
    "40": 0.80 # 40-44
    "45": 0.80 # 45-49
    "50": 0.82 # 50-54
    "55": 0.82 # 55-59
    "60": 0.88 # 60-64
    "65": 0.88 # 65-69
    "70": 0.74 # 70-74
    "75": 0.74 # 75+

sojourn:
  # Mean time in days spent in each compartment
  # Note that the early period is intended to represent the pre-hospitalisations period, whereas the late period is
  # intended to represent the time in hospital or ICU (as applicable)
  compartment_periods:
    hospital_early: 8.1
    hospital_late: 18.4
    icu_early: 12.7
    icu_late: 10.8

  # Mean time spent in each compartment, defined via proportions
  compartment_periods_calculated:
    exposed:
      total_period: 5.5 # Routinely calibrated, see calibration file
      proportions:
        early: 0.5 # Proportion of the exposed period spent infectious - i.e. "presymptomatic"
        late: 0.5

    active:
      total_period: 8. # Routinely calibrated, see calibration file
      proportions:
        # Proportion of the infectious period spent in the early compartment (i.e. can't be isolated for symptoms)
        early: 0.333
        late: 0.667

# Parameters relating to adjusting the mixing matrix to reflect interventions
mobility:
  region: null
  mixing: {}
  age_mixing: null
  npi_effectiveness: {}
  # Mapping of Google mobility locations to Prem-specific locations
  google_mobility_locations:
    work:
      - workplaces
    other_locations:
      - retail_and_recreation
      - grocery_and_pharmacy
      - parks
      - transit_stations
  #  home:
  #    - residential
  smooth_google_data: false # whether to apply a 7-day moving average
  square_mobility_effect: false
  microdistancing: {}
  microdistancing_locations:
    - other_locations
    - school
    - work

clinical_stratification:
  icu_prop: 0.17 # Proportion of those hospitalised that are admitted to ICU
  icu_mortality_prop: 0.5 # Death proportion ceiling for ICU mortality
  props:
    symptomatic:
      # Infectiousness progression adjustments - in ten year brackets that need to be adapted to model strata later
      # From the LSHTM's "Age-dependent effects in the ..." Fig 2b, upper-left panel
      # Mean estimated values used. a.k.a "clinical fraction".
      multiplier: 1.
      props:
        - 0.29 # 0-9
        - 0.21 # 10-19
        - 0.27 # 20-29
        - 0.33 # 30-39
        - 0.40 # 40-49
        - 0.49 # 50-59
        - 0.63 # 60-69
        - 0.69 # 70+
    hospital:
      # Proportion of symptomatic persons that are hospitalised - Dutch GGD report
      multiplier: 1. # Multiplier to the above age-stratified parameters
      props:
        - 0.087 # 0-4
        - 0.009 # 5-9
        - 0.005 # 10-14
        - 0.008 # 15-19
        - 0.011 # 20-24
        - 0.011 # 25-29
        - 0.013 # 30-34
        - 0.015 # 35-39
        - 0.018 # 40-44
        - 0.040 # 45-49
        - 0.047 # 50-54
        - 0.070 # 55-59
        - 0.071 # 60-64
        - 0.114 # 65-69
        - 0.113 # 70-74
        - 0.071 # 75+

  # Infectiousness adjustments, including the effect of isolation following detection
  late_exposed_infect_multiplier: 1.0
  non_sympt_infect_multiplier: 0.5
  late_infect_multiplier:
    sympt_isolate: 0.2
    hospital_non_icu: 0.2
    icu: 0.2

infection_fatality:
  multiplier: 1.
  # Infection fatality proportions - now calculated using the Spanish serosurvey data by Pollan et al.
  props:
    - 1.35e-05 # 0-9
    - 2.7e-05 # 10-19
    - 9.5e-05 # 20-29
    - 2.3e-04 # 30-39
    - 5.6e-04 # 40-49
    - 1.9e-03 # 50-59
    - 7.7e-03 # 60-69
    - 0.027 # 70-79
    - 0.11 # 80+

# Heterogeneity in susceptibility
susceptibility_heterogeneity: null

# Parameters of tanh-based scale-up function used to define time-variant detection, if that approach selected
case_detection:
  maximum_gradient: 0.05 # The shape parameter to the tanh-based curve
  max_change_time: 90. # Point at which curve inflects
  start_value: 0.1 # Starting value - lower asymptote for increasing function
  end_value: 0.6 # End value - upper asymptote for increasing function

testing_to_detection: null

importation: null

# Multiplier scaling the covariance matrix in the Haario Metropolis. 2.4 is the value recommended by Haario.
haario_scaling_factor: 2.4 # Greater values increase jumping step size and reduce the acceptance ratio

# Fake parameters used in calibration for negative binomial (need to be listed for validation to pass)
# Not used by model.
notifications_dispersion_param: 1.
icu_occupancy_dispersion_param: 1.
proportion_seropositive_dispersion_param: 1.
hospital_occupancy_dispersion_param: 1.
new_hospital_admissions_dispersion_param: 1.
new_icu_admissions_dispersion_param: 1.
infection_deaths_dispersion_param: 1.
accum_deaths_dispersion_param: 1.
