description: BASELINE

time:
  start: 485 # 29 Apr 2021
  end: 912

country:
  iso3: VNM

mixing_matrices:
  source_iso3: HKG

# mixing_matrices:
  # type: extrapolated
  # source_iso3: HKG

population:
  region: Ho Chi Minh City
  year: 2019

mobility:
  region: Ho Chi Minh City
  # Google mobility data
  smooth_google_data: true # whether to apply a 7-day moving average
  square_mobility_effect: true
  google_mobility_locations:
    work:
      - workplaces
    other_locations:
      - retail_and_recreation
      - grocery_and_pharmacy
      - transit_stations
  # Micro distancing
  microdistancing:
    behaviour:
      function_type: empiric
      parameters:
        max_effect: .2 # estimated from the Philipines paper
        times:
          - 2021-04-27 # first community case of COVID-19 detected in Ho Chi Minh City
          - 2021-06-01 # social distancing city-wide under Directive No. 15 of the PM, with Directive No.16 in place at Go Vap District
          - 2021-06-29 # Directive No.10 of HCMC's authorities in place
          - 2020-07-09 # Directive No.16 of the PM in place city-wide
          - 2020-07-26 # curfew from 6PM to 6AM
          - 2020-08-23 # total lockdown implemented
          - 2020-10-01 # lockdown started to ease
        values:
          - 0.2
          - 0.4
          - 0.5
          - 0.7
          - 0.85
          - 1.
          - 0.6
      locations:
        - other_locations
        - school
        - work
        - home
  mixing:
    # Students stared to switch to full online learning since 2020-05-09.
    school:
      append: false
      times:
        - 2020-05-09 # All schools switched to online learning, school year 2020-2021 ended
        - 2020-05-10 # Multiple universities allow students to come back to finish the degree. Source: Tuoitre.
      values:
        - 0.
        - 0.1


testing_to_detection:
  assumed_tests_parameter:
  assumed_cdr_parameter: 0.05 # needs calibrating by MLE
  smoothing_period: 14


# Vaccination-related
# All information provided here are historical. Last update: 15th Oct, 2021.
# All figures calculated below are available at: https://bit.ly/HCMC_vaccination_status
vaccination:
  fully_vaccinated:
    ve_sympt_covid: 0.7157 # weighted average
    ve_prop_prevent_infection: 1 # now varied
    ve_hospitalisation: 0.9160 # weighted average
    ve_death: 0.9329 # weighted average
  second_dose_delay:  32.67 # weighted average waiting time between two doses
  roll_out_components: # --> stratify by time
    - age_min: 20
      supply_period_coverage:
        coverage: .001226
        start_time: 485 # 29th April 2021
        end_time: 518 # 01st June 2021
    - age_min: 20
      supply_period_coverage:
        coverage: .006267
        start_time: 518 # 01 June 2021
        end_time: 545 # 28 June 2021
    - age_min: 20
      supply_period_coverage:
        coverage: 0.001289
        start_time: 545 # 28 June 2021
        end_time: 556 # 09 July 2021
    - age_min: 20
      supply_period_coverage:
        coverage: 0.001910
        start_time: 556 # 09 July 2021
        end_time: 572 # 25 July 2021
    - age_min: 20
      supply_period_coverage:
        coverage: 0.0284
        start_time: 572 # 25 July 2021
        end_time: 593 # 15 Aug 2021
    - age_min: 20
      supply_period_coverage:
        coverage: 0.0384
        start_time: 593 # 15 Aug 2021
        end_time: 610 # 01 Sep 2021
    - age_min: 20
      supply_period_coverage:
        coverage: 0.1957
        start_time: 610 # 01 Sep 2021
        end_time: 624 # 15 Sep 2021
    - age_min: 20
      supply_period_coverage:
        coverage: 0.2915
        start_time: 624 # 15 Sep 2021
        end_time: 640 # 01 Oct 2021
    - age_min: 20
      supply_period_coverage:
        coverage: 0.2394
        start_time: 640 # 01 Oct 2021
        end_time: 654 # 15 Oct 2021
