description: BASELINE

time:
  start: 483 #457  # 28 Apr 2021
  end: 912

country:
  iso3: VNM

# mixing_matrices:
  # source_iso3: CHN

mixing_matrices:
  # type: extrapolated --> default
  source_iso3: HKG

population:
  region: Ho Chi Minh City
  year: 2019

mobility:
  region: Ho Chi Minh City
  # Google mobility data
  smooth_google_data: true # whether to apply a 7-day moving average
  square_mobility_effect: true
  google_mobility_locations:
    work:
      - workplaces
    other_locations:
      - retail_and_recreation
      - grocery_and_pharmacy
      - transit_stations
  # Micro distancing  --> modify if necessary
  microdistancing:
    behaviour:
      function_type: empiric
      parameters:
        max_effect: .2 #estimated from the Phillipines paper
        times: [483, 517, 545, 555, 572, 593, 639]
        values: [0.2, 0.4, 0.5, 0.7, 0.85, 1., 0.6]
      locations:
        - other_locations
        - school
        - work
        - home
  mixing:
    # Consider schools are closed for now
    school:
      append: false
      times:
        - 2020-01-01
      values:
        - 0.

# definition?
testing_to_detection:
  assumed_tests_parameter: 1.e-4 #proportion of population get tested everyday
  assumed_cdr_parameter: 0.05 # proportion of symptomatic cases that are detected by testing, considering 1e-4 porportion detected
  smoothing_period: 14


# Vaccination-related
# transmission by large gatherings at vaccination sites (Phu Tho stadium as an example)?
vaccination:
  fully_vaccinated:
    overall_efficacy: 0.7084 # weighted average efficacy of AZ, Pfizer, Moderna and Verocell
    vacc_prop_prevent_infection: 1 # now varied # 1--> all goes to preventing infection, 0 --> all goes to preventing infection showing symptoms
  second_dose_delay:  32.67 # weighted average time waiting between two doses
  roll_out_components: # --> stratify by time
    - age_min: 20
      supply_period_coverage:
        coverage: .001226 # --> proportion of the population vaccinated at the end_time (here 18th August)
        start_time: 483 # 28 April 2021
        end_time: 517 # 01 June 2021
    - age_min: 20
      supply_period_coverage:
        coverage: .006267 # --> proportion of the population vaccinated at the end_time (here 18th August)
        start_time: 517 # 01 June 2021
        end_time: 544 # 28 June 2021
    - age_min: 20
      supply_period_coverage:
        coverage: 0.001289 # --> proportion of the population vaccinated at the end_time (here 18th August)
        start_time: 544 # 28 June 2021
        end_time: 555 # 09 July 2021
    - age_min: 20
      supply_period_coverage:
        coverage: 0.001910
        start_time: 555 # 09 July 2021
        end_time: 571 # 25 July 2021
    - age_min: 20
      supply_period_coverage:
        coverage: 0.0284
        start_time: 571 # 25 July 2021
        end_time: 592 # 15 Aug 2021
    - age_min: 20
      supply_period_coverage:
        coverage: 0.0384
        start_time: 592 # 15 Aug 2021
        end_time: 609 # 01 Sep 2021
    - age_min: 20
      supply_period_coverage:
        coverage: 0.1957
        start_time: 609 # 01 Sep 2021
        end_time: 623 # 15 Sep 2021
    - age_min: 20
      supply_period_coverage:
        coverage: 0.2915
        start_time: 623 # 15 Sep 2021
        end_time: 639 # 01 Oct 2021
    - age_min: 20
      supply_period_coverage:
        coverage: 0.2394
        start_time: 639 # 01 Oct 2021
        end_time: 653 # 15 Oct 2021