---
iso3: "KIR"

age_mixing:
  # type: "prem"
  type: extrapolated
  source_iso3: FJI
  age_adjust: true

time:
  start: 1955.
  end: 2050.
  step: 0.1
  critical_ranges: [[2022., 2025.]]

start_population_size: 36573.

#import_ltbi_cases:
#  start_time: 2000
#  n_cases_per_year: 100

# MODEL STRUCTURE
stratify_by: ["age", "organ", "location"]
age_breakpoints: [0, 5, 15, 35, 50]
user_defined_stratifications: # this specifies user-defined  stratifications
  location:
    strata: ["starawa", "other"]
    proportions:
      starawa: .6
      other: .4
    prop_mixing_same_stratum: .95
    adjustments:
      infection:
        starawa: 1.
        other: 1.
      detection:
        starawa: 1.5
        other: 1.

# BCG coverage
bcg_effect: "infection"  # infection or mortality
time_variant_bcg_perc:
  #1930: 0.
  #1990: 49.
  #1991: 71.
  #1992: 72.
  #1993: 88.
  #1994: 96.
  #1995: 71.
  #1996: 98.
  #1997: 94.
  #1998: 81.
  #1999: 81.
  2000: 80.
  2001: 85.
  2002: 88.
  2003: 91.
  2004: 94.
  2005: 93.
  2006: 91.
  2007: 90.
  2008: 83.
  2009: 76.
  2010: 87.
  2011: 86.
  2012: 95.
  2013: 86.
  2014: 72.
  2015: 79.
  2016: 79.
  2017: 89.
  2018: 90.
  2019: 92.
  2020: 93.

time_variant_tsr: # should always be > 0 # https://www.stoptb.org/static_pages/KIR_Dashboard.html
  1995: .25
  2012: 0.9
  2013.: 0.84
  2014.: 0.87
  2015.: 0.9
  2016.: 0.9
  2017.: 0.87
  2018.: 0.92
  2019.: 0.92

time_variant_tb_screening_rate:
  shape: .1 # The shape parameter to the tanh-based curve
  inflection_time: 1995. # Point at which curve inflects
  start_asymptote: 0. # Starting value - lower asymptote
  end_asymptote: 0.4057634920539735

extra_params:
  prop_diabetes: # 22.5 (20 - 79 years)
    0: 0.01
    5: 0.05
    15: 0.2
    35: 0.4
    50: 0.7
  rr_progression_diabetes: 5.643402828077587
  future_diabetes_multiplier: 1.2


# calibrated parameters
contact_rate: 1.5
progression_multiplier: 0.7117191601170418

# REQUESTED OUTPUTS
calculated_outputs:
  [
    "prevalence_infectious",
    "percentage_latent",
    "population_size",
    "notifications",
    "mortality",
    "incidence",
    "cumulative_diseased",
    "cumulative_deaths",
    "screening_rate",
  ]
outputs_stratification:
  prevalence_infectious: ["location"]
  percentage_latent: ["location"]
  notifications: ["location"]
  incidence: ["location"]
  mortality: ["location"]

cumulative_output_start_time: 2022.

inflate_reactivation_for_diabetes: True

# Implement past interventions
time_variant_acf:
  - stratum_filter: { "location": "starawa" }
    time_variant_screening_rate:
      2017: 0.
      2017.01: 1.9
      2018.: 1.9
      2018.01: 0.
    exclude_age: [0, 3]
  - stratum_filter: { "location": "other" }
    time_variant_screening_rate:
      2018: 0.
      2018.01: 1.66  # from 81% first screen
      2019: 1.66
      2019.01: 0.

time_variant_ltbi_screening:
  - stratum_filter: { "location": "starawa" }
    time_variant_screening_rate:
      2018: 0.
      2018.01: .9  # from 81% first screen / of whom 86.5% fully screened times 92% of TST+ recommended for PT times 92% of recommanded actually started
      2019: .9
      2019.01: 0.
  - stratum_filter: { "location": "other" }
    time_variant_screening_rate:
      2018: 0.

awareness_raising:
  relative_screening_rate: 1.25
  scale_up_range: [2020, 2022]

#hh_contacts_pt:
#  start_time: 2020
#  prop_smearpos_among_prev_tb: .40
#  prop_hh_transmission: .30
#  prop_hh_contacts_screened: .70
#  prop_pt_completion: .5
