description: BASELINE
parent: apps/covid_19/params.yml

contact_rate: 0.0208
infectious_seed: 250.

time:
  start: 180
  end: 822

country:
  iso3: IDN

mobility:
  google_mobility_locations:  # Not mapping residential mobility to home
    work:
      - workplaces
    other_locations:
      - retail_and_recreation
      - grocery_and_pharmacy
      - parks
      - transit_stations
  microdistancing:
    behaviour:
      function_type: tanh
      parameters:
        shape: .005
        inflection_time: 430
        lower_asymptote: 0.
        upper_asymptote: 0.4
      locations:
        - other_locations
        - school
        - work
        - home

testing_to_detection:
  assumed_tests_parameter: 1.e-04
  assumed_cdr_parameter: 0.04
  smoothing_period: 14

contact_tracing:
    assumed_trace_prop: 0.2
    assumed_prev: 1.e-3
    quarantine_infect_multiplier: 0.2

voc_emergence:
  delta:
    start_time: 360
    entry_rate: 1.
    seed_duration: 10.
    contact_rate_multiplier: 2.3
