description: BASELINE

contact_rate: 0.032

time:
  start: 290

mixing_matrices:
  type: extrapolated
  source_iso3: CHN

population:
  region: Johor
  year: 2019

mobility:
  microdistancing:
    behaviour:
      parameters:
        upper_asymptote: 0.32
