# SCENARIO DESCRIPTION: BASELINE
---
parent: apps/covid_19/params.yml
iso3: AUS
region: Victoria
pop_region_override: LODDON_MALLEE
pop_year: 2018
implement_importation: true
infectious_seed: 0

start_time: 160.
end_time: 365.

contact_rate: 0.034
seasonal_force: 0.3

compartment_periods:
  icu_early: 10.

hospital_props_multiplier: 1.5
icu_prop: 0.12

compartment_periods_calculated:
  exposed:
    total_period: 3.8

testing_to_detection:
  assumed_tests_parameter: 1000
  assumed_cdr_parameter: 0.25

microdistancing:
  function_type: empiric
  parameters:
    multiplier: 0.05
    times: [181, 182, 185, 186, 191, 192, 202, 204, 215, 216]
    values: [0., 2., 2., 3., 3., 5., 5., 7., 7., 9.]

  # 30th March, day 90, stage 3 enforced
  # 9th June, day 162, stage 3 released (I think)
  # 20th June, day 172, restrictions tightened, only five visitors at home
  # (21st June, day 173, seasonal forcing peaks)
  # 30th June, day 182, postcode lockdowns - two units microdistancing
  # 4th July, day 186, two more postcodes locked down - one unit further microdistancing
  # 9th July, day 191, stage 3 enforced - two units further microdistancing
  # 22nd July, day 204, face coverings - two units further microdistancing
  # 2nd August, day 215, stage 4 enforced - two units further microdistancing

mixing:
  school:
    append: false
    times:
      - 2020-03-24
      - 2020-03-25 # School holidays brought forward to 24th March
      - 2020-05-25
      - 2020-05-27 # 6 / 14 to represent five grades and special schools going back
      - 2020-06-08
      - 2020-06-10 # All students back to school
      - 2020-06-26
      - 2020-06-27
      - 2020-07-13 # Back to school for all and only Years 11 and 12, Year 10 for Melbourne and Mitchell Shire
      - 2020-08-03
      - 2020-08-04
      - 2020-08-25 # Google mobility update, pls review and remove
    values:
      - 1.
      - 0.
      - 0.
      - 0.429
      - 0.429
      - 1.
      - 1.
      - 0
      - .5
      - .5
      - 0.
      - 0. # Google mobility update, pls review and remove

data:
  times_imported_cases:
    [
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32,
      33,
      34,
      35,
      36,
      37,
      38,
      39,
      40,
      41,
      42,
      43,
      44,
      45,
      46,
      47,
      48,
      49,
      50,
      51,
      52,
      53,
      54,
      55,
      56,
      57,
      58,
      59,
      60,
      61,
      62,
      63,
      64,
      65,
      66,
      67,
      68,
      69,
      70,
      71,
      72,
      73,
      74,
      75,
      76,
      77,
      78,
      79,
      80,
      81,
      82,
      83,
      84,
      85,
      86,
      87,
      88,
      89,
      90,
      91,
      92,
      93,
      94,
      95,
      96,
      97,
      98,
      99,
      100,
      101,
      102,
      103,
      104,
      105,
      106,
      107,
      108,
      109,
      110,
      111,
      112,
      113,
      114,
      115,
      116,
      117,
      118,
      119,
      120,
      121,
      122,
      123,
      124,
      125,
      126,
      127,
      128,
      129,
      130,
      131,
      132,
      133,
      134,
      135,
      136,
      137,
      138,
      139,
      140,
      141,
      142,
      143,
      144,
      145,
      146,
      147,
      148,
      149,
      150,
      151,
      152,
      153,
      154,
      155,
      156,
      157,
      158,
      159,
      160,
      161,
      162,
      163,
      164,
      165,
      166,
      167,
      168,
      169,
      170,
      171,
      172,
      173,
      174,
      175,
      176,
      177,
      178,
      179,
      180,
      181,
      182,
      183,
      184,
      185,
      186,
      187,
      188,
      189,
      190,
    ]
  n_imported_cases:
    [
      0.0001,
      1,
      0,
      0,
      1,
      0,
      1,
      1,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      2,
      0,
      0,
      1,
      0,
      0,
      0,
      0,
      2,
      0,
      0,
      1,
      0,
      1,
      1,
      2,
      3,
      1,
      4,
      9,
      12,
      4,
      7,
      13,
      29,
      23,
      24,
      32,
      35,
      51,
      39,
      49,
      44,
      33,
      72,
      48,
      23,
      42,
      17,
      27,
      20,
      11,
      9,
      5,
      16,
      11,
      4,
      5,
      10,
      4,
      8,
      5,
      2,
      1,
      3,
      9,
      5,
      0,
      2,
      1,
      0,
      1,
      0,
      1,
      0,
      0,
      1,
      2,
      4,
      1,
      1,
      2,
      1,
      8,
      0,
      0,
      1,
      3,
      4,
      0,
      2,
      3,
      7,
      7,
      3,
      2,
      1,
      0,
      0,
      3,
      3,
      0,
      2,
      3,
      2,
      3,
      3,
      2,
      3,
      1,
      0,
      7,
      6,
      2,
      0,
      3,
      1,
      0,
      0,
      2,
      2,
      6,
      3,
      1,
      3,
      15,
      7,
      1,
      2,
      3,
      4,
      2,
      1,
      10,
      8,
      1,
      0,
      1,
      0,
      6,
      3,
      7,
      0,
      2,
      0,
      1,
      1,
    ]
