---
# Parameters used to build a general model of COVID-19 disease
description: BASELINE

voc_emergence: null # Emergence of Variants of Concern
stratify_by_infection_history: false # Note that the current code may not allocate imported cases to the right stratum
waning_immunity_duration: null
rel_prop_symptomatic_experienced: null
infect_death: 0. # Compulsory parameter that is completely overwritten in stratification, rather than being modified
universal_death_rate: 0. # Compulsory parameter for all models, even though there are no population-wide deaths
infectious_seed: 10 # Initial condition for infectious
contact_rate: 0.03 # Routinely calibrated, see respective calibration files
seasonal_force: null

#
mixing_matrices:
  type: "prem"
  age_adjust: true  # Note that this is not relevant unless "empiric" selected for type

# Integration times
time:
  start: 40.
  end: 550.
  step: 1.

# Parameters used in querying the population database
country:
  iso3: null
population:
  region: null
  year: 2020

# Age-related parameters
age_stratification:
  # Age-based susceptibility from Zhang et al. The reported ORs were converted to RRs using Tables S14 and S15.
  # DOI: 10.1126/science.abb8001 (Mendeley citation key Zhang2020a)
  susceptibility:
    "0": 0.36 # 0-4
    "5": 0.36 # 5-9
    "10": 0.36 # 10-14
    "15": 1. # 15-19
    "20": 1. # 20-24
    "25": 1. # 25-29
    "30": 1. # 30-34
    "35": 1. # 35-39
    "40": 1. # 40-44
    "45": 1. # 45-49
    "50": 1. # 50-54
    "55": 1. # 55-59
    "60": 1. # 60-64
    "65": 1.41 # 65-69
    "70": 1.41 # 70-74
    "75": 1.41 # 75+

sojourn:
  # Mean time in days spent in each compartment
  # Note that the early period is intended to represent the pre-hospital/ICU/isolation period, whereas the late phase
  # is intended to represent the time in hospital, ICU or isolation
  # Estimates taken from ISARIC report 4th Oct 2020 (Mendeley citation key Pritchard2020}
  compartment_periods:
    hospital_early: 7.7
    hospital_late: 12.8
    icu_early: 10.5  # 7.7 + 2.8 (time from symptom to Hosp admission + time from Hosp admission to ICU)
    icu_late: 13.3

  # Mean time spent in each compartment, defined via proportions
  compartment_periods_calculated:
    exposed:
      total_period: 5.5 # Routinely calibrated, see calibration file
      proportions:
        early: 0.5 # Proportion of the exposed period spent infectious - i.e. "presymptomatic"
        late: 0.5

    active:
      total_period: 8. # Routinely calibrated, see calibration file
      proportions:
        early: 0.333 # Proportion of active period spent in the early compartment (can't be isolated, not in hospital)
        late: 0.667

clinical_stratification:
  icu_prop: 0.17 # Proportion of those hospitalised that are admitted to ICU
  icu_mortality_prop: 0.5 # Death proportion ceiling for ICU mortality
  props:
    symptomatic:
      # Changed (26th August) to "Asyptomatic SARS-Cov-2 infection: A Systematic review and meta-analysis", Sah et al.
      multiplier: 1.
      props:
        - 0.533  # 0-4
        - 0.533  # 5-9
        - 0.533  # 10-14
        - 0.533  # 15-19
        - 0.679  # 20-24
        - 0.679  # 25-29
        - 0.679  # 30-34
        - 0.679  # 35-39
        - 0.679  # 40-44
        - 0.679  # 45-49
        - 0.679  # 50-55
        - 0.679  # 55-59
        - 0.803  # 60-64
        - 0.803  # 65-69
        - 0.803  # 70-74
        - 0.803  # 75+
    hospital:
      # Proportion of symptomatic persons that are hospitalised - Dutch GGD report from 4th August 2020, Table 3
      multiplier: 1. # Multiplier to the below age-stratified parameters
      props:
        - 0.0777 # 0-4
        - 0.0069 # 5-9
        - 0.0034 # 10-14
        - 0.0051 # 15-19
        - 0.0068 # 20-24
        - 0.0080 # 25-29
        - 0.0124 # 30-34
        - 0.0129 # 35-39
        - 0.0190 # 40-44
        - 0.0331 # 45-49
        - 0.0383 # 50-54
        - 0.0579 # 55-59
        - 0.0617 # 60-64
        - 0.1030 # 65-69
        - 0.1072 # 70-74
        - 0.0703 # 75+

  # Infectiousness adjustments, including the effect of isolation following detection
  non_sympt_infect_multiplier: 0.5
  late_infect_multiplier:
    sympt_isolate: 0.2
    hospital_non_icu: 0.2
    icu: 0.2

infection_fatality:
  multiplier: 1.
  top_bracket_overwrite: null
  # Infection fatality proportions - last column of Table S3 (Mendeley citation key ODriscoll2020)
  props:
    - 0.00003 # 0-4
    - 0.00001 # 5-9
    - 0.00001 # 10-14
    - 0.00003 # 15-19
    - 0.00006 # 20-24
    - 0.00013 # 25-29
    - 0.00024 # 30-34
    - 0.00040 # 35-39
    - 0.00075 # 40-44
    - 0.00121 # 45-49
    - 0.00207 # 50-54
    - 0.00323 # 55-59
    - 0.00456 # 60-64
    - 0.01075 # 65-69
    - 0.01674 # 70-74
    - 0.03203 # 75-79
    - 0.08292 # 80+

# Parameters relating to adjusting the mixing matrix to reflect interventions
age_specific_risk_multiplier: null
mobility:
  region: null
  mixing: {}
  age_mixing: null
  npi_effectiveness: {}
  # Mapping of Google mobility locations to Prem-specific locations
  google_mobility_locations:
    work:
      - workplaces
    other_locations:
      - retail_and_recreation
      - grocery_and_pharmacy
      - parks
      - transit_stations
    home:
      - residential
  smooth_google_data: false # whether to apply a 7-day moving average
  square_mobility_effect: true
  microdistancing: {}

testing_to_detection: null

victorian_clusters: null

# Vaccination-related
vaccination:
  fully_vaccinated:
    overall_efficacy: 0.
    vacc_prop_prevent_infection: 0.
    vacc_reduce_infectiousness: 0.
  one_dose: null
  second_dose_delay: 41.  # Time from receiving first dose to second
  roll_out_components: []

vaccination_risk:
  calculate: false
  prop_astrazeneca: 1.
  prop_mrna: 0.
  tts_rate: # Source: https://www.health.gov.au/news/atagi-update-following-weekly-covid-19-meeting-25-august-2021
    0: 2.5e-5
    5: 2.5e-5
    10: 2.5e-5
    15: 2.5e-5
    20: 2.5e-5
    25: 2.5e-5
    30: 2.5e-5
    35: 2.5e-5
    40: 2.5e-5
    45: 2.5e-5
    50: 2.7e-5
    55: 2.7e-5
    60: 1.6e-5
    65: 1.6e-5
    70: 2.1e-5
    75: 1.8e-5

  tts_fatality_ratio: # Source: https://www.gov.uk/government/publications/coronavirus-covid-19-vaccine-adverse-reactions/coronavirus-vaccine-summary-of-yellow-card-reporting
    0: .25  # No data available for this group. We assume the same fatality ratio as for 18-29 years old.
    5: .25  # No data available for this group. We assume the same fatality ratio as for 18-29 years old.
    10: .25  # No data available for this group. We assume the same fatality ratio as for 18-29 years old.
    15: .25  # No data available for this group. We assume the same fatality ratio as for 18-29 years old.
    20: .25
    25: .25
    30: .21
    35: .21
    40: .12
    45: .12
    50: .19
    55: .19
    60: .15
    65: .15
    70: .18
    75: .18

  myocarditis_rate:
    0: 3.57e-5  # assumed same as 12-17 category
    5: 3.57e-5 # assumed same as 12-17 category
    10: 3.57e-5  # from 12-17 category
    15: 3.2e-5  # average of 12-17 and 18-24 categories
    20: 2.7e-5  # from 18-24 category
    25: 0.90e-5
    30: 0.43e-5
    35: 0.43e-5
    40: 0.29e-5
    45: 0.29e-5
    50: 0.10e-5
    55: 0.10e-5
    60: 0.10e-5
    65: 0.05e-5
    70: 0.05e-5
    75: 0.05e-5

# Contact tracing-related
contact_tracing: null

# Multiplier scaling the covariance matrix in the Haario Metropolis. 2.4 is the value recommended by Haario.
haario_scaling_factor: 2.4  # Greater values increase jumping step size and reduce the acceptance ratio
metropolis_init_rel_step_size: .1
n_steps_fixed_proposal: 50

# Time from which cumulative cases should start (incidence and notification), if null, the output is not calculated
cumul_incidence_start_time: null

# Vic 2021 seeding
vic_2021_seeding: null

# Fake parameters used in calibration for negative binomial (need to be listed for validation to pass)
# Not used by model.
notifications_dispersion_param: 1.
icu_occupancy_dispersion_param: 1.
proportion_seropositive_dispersion_param: 1.
hospital_occupancy_dispersion_param: 1.
new_hospital_admissions_dispersion_param: 1.
new_icu_admissions_dispersion_param: 1.
infection_deaths_dispersion_param: 1.
accum_deaths_dispersion_param: 1.

target_output_ratio: null
