---
# Parameters used to build a general model of COVID-19 disease
parent: null # This file is the bottom of the parameter tree for the Covid app
description: BASELINE

voc_emergence: null # Emergence of Variants of Concern
stratify_by_infection_history: false # Note that the current code may not allocate imported cases to the right stratum
waning_immunity_duration: null
rel_prop_symptomatic_experienced: null
infect_death: 0. # Compulsory parameter that is completely overwritten in stratification, rather than being modified
universal_death_rate: 0. # Compulsory parameter for all models, even though there are no population-wide deaths
infectious_seed: 10 # Initial condition for infectious
contact_rate: 0.03 # Routinely calibrated, see respective calibration files

# Integration times
time:
  start: 40.
  end: 550.
  step: 1.

# Parameters used in querying the population database
country:
  iso3: null
population:
  region: null
  year: 2020

# Age-related parameters
age_stratification:
  # Age-based susceptibility from Zhang et al. The reported ORs were converted to RRs using Tables S14 and S15.
  # DOI: 10.1126/science.abb8001 (Mendeley citation key Zhang2020a)
  susceptibility:
    "0": 0.36 # 0-4
    "5": 0.36 # 5-9
    "10": 0.36 # 10-14
    "15": 1. # 15-19
    "20": 1. # 20-24
    "25": 1. # 25-29
    "30": 1. # 30-34
    "35": 1. # 35-39
    "40": 1. # 40-44
    "45": 1. # 45-49
    "50": 1. # 50-54
    "55": 1. # 55-59
    "60": 1. # 60-64
    "65": 1.41 # 65-69
    "70": 1.41 # 70-74
    "75": 1.41 # 75+

sojourn:
  # Mean time in days spent in each compartment
  # Note that the early period is intended to represent the pre-hospital/ICU/isolation period, whereas the late phase
  # is intended to represent the time in hospital, ICU or isolation
  # Estimates taken from ISARIC report 4th Oct 2020 (Mendeley citation key Pritchard2020}
  compartment_periods:
    hospital_early: 7.7
    hospital_late: 12.8
    icu_early: 10.5 # 7.7 + 2.8 (time from symptom to Hosp admission + time from Hosp admission to ICU)
    icu_late: 13.3

  # Mean time spent in each compartment, defined via proportions
  compartment_periods_calculated:
    exposed:
      total_period: 5.5 # Routinely calibrated, see calibration file
      proportions:
        early: 0.5 # Proportion of the exposed period spent infectious - i.e. "presymptomatic"
        late: 0.5

    active:
      total_period: 8. # Routinely calibrated, see calibration file
      proportions:
        early: 0.333 # Proportion of active period spent in the early compartment (can't be isolated, not in hospital)
        late: 0.667

clinical_stratification:
  icu_prop: 0.17 # Proportion of those hospitalised that are admitted to ICU
  icu_mortality_prop: 0.5 # Death proportion ceiling for ICU mortality
  props:
    symptomatic:
      # Infectiousness progression adjustments - in ten year brackets that need to be adapted to model strata later
      # From the LSHTM's "Age-dependent effects in the ..." Fig 2b, upper-left panel
      # Mean estimated values used. a.k.a "clinical fraction".
      multiplier: 1.
      props:
        - 0.29 # 0-9
        - 0.21 # 10-19
        - 0.27 # 20-29
        - 0.33 # 30-39
        - 0.40 # 40-49
        - 0.49 # 50-59
        - 0.63 # 60-69
        - 0.69 # 70+
    hospital:
      # Proportion of symptomatic persons that are hospitalised - Dutch GGD report from 4th August 2020, Table 3
      multiplier: 1. # Multiplier to the below age-stratified parameters
      props:
        - 0.0777 # 0-4
        - 0.0069 # 5-9
        - 0.0034 # 10-14
        - 0.0051 # 15-19
        - 0.0068 # 20-24
        - 0.0080 # 25-29
        - 0.0124 # 30-34
        - 0.0129 # 35-39
        - 0.0190 # 40-44
        - 0.0331 # 45-49
        - 0.0383 # 50-54
        - 0.0579 # 55-59
        - 0.0617 # 60-64
        - 0.1030 # 65-69
        - 0.1072 # 70-74
        - 0.0703 # 75+

  # Infectiousness adjustments, including the effect of isolation following detection
  non_sympt_infect_multiplier: 0.5
  late_infect_multiplier:
    sympt_isolate: 0.2
    hospital_non_icu: 0.2
    icu: 0.2

infection_fatality:
  multiplier: 1.
  top_bracket_overwrite: null
  # Infection fatality proportions - last column of Table S3 (Mendeley citation key ODriscoll2020)
  props:
    - 0.00003 # 0-4
    - 0.00001 # 5-9
    - 0.00001 # 10-14
    - 0.00003 # 15-19
    - 0.00006 # 20-24
    - 0.00013 # 25-29
    - 0.00024 # 30-34
    - 0.00040 # 35-39
    - 0.00075 # 40-44
    - 0.00121 # 45-49
    - 0.00207 # 50-54
    - 0.00323 # 55-59
    - 0.00456 # 60-64
    - 0.01075 # 65-69
    - 0.01674 # 70-74
    - 0.03203 # 75-79
    - 0.08292 # 80+

# Parameters relating to adjusting the mixing matrix to reflect interventions
age_specific_risk_multiplier: null
mobility:
  region: null
  mixing: {}
  age_mixing: null
  npi_effectiveness: {}
  # Mapping of Google mobility locations to Prem-specific locations
  google_mobility_locations:
    work:
      - workplaces
    other_locations:
      - retail_and_recreation
      - grocery_and_pharmacy
      - parks
      - transit_stations
    home:
      - residential
  smooth_google_data: false # whether to apply a 7-day moving average
  square_mobility_effect: true
  microdistancing: {}

# Parameters of tanh-based scale-up function used to define time-variant detection, if that approach selected
case_detection:
  shape: 0.05 # The shape parameter to the tanh-based curve
  inflection_time: 90. # Point at which curve inflects
  lower_asymptote: 0.1 # Starting value - lower asymptote for increasing function
  upper_asymptote: 0.6 # End value - upper asymptote for increasing function

testing_to_detection: null

victorian_clusters: null

# Vaccination-related
vaccination:
  overall_efficacy: 0
  vacc_prop_prevent_infection: 0
  roll_out_components: []

# Contact tracing-related
contact_tracing: null

# Multiplier scaling the covariance matrix in the Haario Metropolis. 2.4 is the value recommended by Haario.
haario_scaling_factor: 2.4 # Greater values increase jumping step size and reduce the acceptance ratio
metropolis_init_rel_step_size: .1
n_steps_fixed_proposal: 50

# Time from which cumulative cases should start (incidence and notification), if null, the output is not calculated
cumul_incidence_start_time: null

# Fake parameters used in calibration for negative binomial (need to be listed for validation to pass)
# Not used by model.
notifications_dispersion_param: 1.
icu_occupancy_dispersion_param: 1.
proportion_seropositive_dispersion_param: 1.
hospital_occupancy_dispersion_param: 1.
new_hospital_admissions_dispersion_param: 1.
new_icu_admissions_dispersion_param: 1.
infection_deaths_dispersion_param: 1.
accum_deaths_dispersion_param: 1.

target_output_ratio: null
