description: BASELINE
parent: apps/covid_19/eur_optimisation_params.yml

country:
  iso3: FRA

mobility:
  mixing:
    school:
      append: false
      times:
        - 2020-03-15
        - 2020-03-16
        - 2020-09-01
        - 2020-09-03
      values:
        - 1.0
        - 0.1
        - 0.1
        - 1.0

#vaccination:
#  infection_efficacy: .8
#  severity_efficacy: 0.
#  roll_out_components:
#    - age_min: 70
#      supply_period_coverage:
#        coverage: 0.9
#        start_time: 100
#        end_time: 200
#    - age_min: 50
#      age_max: 69
#      supply_timeseries:
#        times: [199, 200, 300, 301]
#        values: [0, 100000, 100000, 0]
