description: BASELINE
parent: apps/covid_19/eur_optimisation_params.yml

country:
  iso3: FRA

mobility:
  mixing:
    school:
      append: false
      times:
        - 2020-03-15
        - 2020-03-16
        - 2020-09-01
        - 2020-09-03
      values:
        - 1.0
        - 0.1
        - 0.1
        - 1.0
