description: BASELINE
parent: apps/covid_19/params.yml

contact_rate: 0.0193
seasonal_force: 0.
infectious_seed: 100.

time:
  start: 260
  end: 550

country:
  iso3: LKA

clinical_stratification:
  non_sympt_infect_multiplier: 0.25
  props:
    symptomatic:
      multiplier: 1.5

vaccination:
  overall_efficacy: 0.75
  vacc_prop_prevent_infection: 1

testing_to_detection:
  assumed_tests_parameter: 1.e-04
  assumed_cdr_parameter: 0.06
  smoothing_period: 14

mobility:
  mixing:
    school:
      append: false
      times:
        - 2020-03-13 # All schools close
        - 2020-03-14
        - 2020-07-06 # schools partial re-open
        - 2020-07-07
        - 2020-07-12 # Full schools close again
        - 2020-07-13
        - 2020-07-27 # Schools partial reopen
        - 2020-07-28
        - 2020-08-10 # Schools fully open again
        - 2020-08-11
        - 2020-11-03 # Schools fully close again
        - 2020-11-04
        - 2020-12-14 # All but western province re-open
        - 2020-12-15
        - 2021-01-11 # All but high isolated schools re-open
        - 2021-01-12
        - 2021-05-05 # All schools close
        - 2021-05-06
      values:
        - 1.
        - 0.
        - 0.
        - 0.2
        - 0.2
        - 0
        - 0
        - 0.5
        - 0.5
        - 1
        - 1
        - 0.
        - 0.
        - 0.5
        - 0.5
        - 1
        - 1
        - 0
#  microdistancing:
#    behaviour:
#      function_type: tanh
#      parameters:
#        shape: .1
#        inflection_time: 398.  # 1st February 2021
#        lower_asymptote: 0.
#        upper_asymptote: 0.11
#      locations:
#        - other_locations
#        - school
#        - work
#        - home

#voc_emergence:
#  start_time: 381   #15 Jan 2021
#  entry_rate: 1.
#  seed_duration: 5.
#  contact_rate_multiplier: 1.56  # LSHTM's estimate
