description: BASELINE

contact_rate: 0.0215
infectious_seed: 200

time:
  start: 240
  end: 746

country:
  iso3: LKA

contact_tracing:
    assumed_trace_prop: 0.05
    assumed_prev: 1.e-3
    quarantine_infect_multiplier: 0.2

vaccination:
  overall_efficacy: 0.7
  vacc_prop_prevent_infection: 1
  roll_out_components:
    - supply_period_coverage:
        coverage: .06
        start_time: 481 # 25 Apr 2021
        end_time: 561 # 14 July 2021
    - supply_period_coverage:
        coverage: .60
        start_time: 562 # 15 July 2021
        end_time: 746 # 15 Jan 2022

testing_to_detection:
  assumed_tests_parameter: 1.e-04
  assumed_cdr_parameter: 0.06
  smoothing_period: 14

clinical_stratification:
  icu_prop: 0.04

mobility:
  microdistancing:
    behaviour:
      function_type: tanh
      parameters:
        shape: .02
        inflection_time: 380. # 1st February 2021
        lower_asymptote: 0.
        upper_asymptote: 0.4
      locations:
        - other_locations
        - school
        - work
        - home
  mixing:
    school:
      append: false
      times:
        - 2020-03-13 # All schools close
        - 2020-03-14
        - 2020-07-06 # schools partial re-open
        - 2020-07-07
        - 2020-07-12 # Full schools close again
        - 2020-07-13
        - 2020-07-27 # Schools partial reopen
        - 2020-07-28
        - 2020-08-10 # Schools fully open again
        - 2020-08-11
        - 2020-11-03 # Schools fully close again
        - 2020-11-04
        - 2020-12-14 # All but western province re-open
        - 2020-12-15
        - 2021-01-11 # All but high isolated schools re-open
        - 2021-01-12
        - 2021-05-05 # All schools close
        - 2021-05-06
      values:
        - 1.
        - 0.
        - 0.
        - 0.2
        - 0.2
        - 0
        - 0
        - 0.5
        - 0.5
        - 1
        - 1
        - 0.
        - 0.
        - 0.5
        - 0.5
        - 1
        - 1
        - 0

voc_emergence:
  dual_voc: true #whether two or one strain VoC
  start_time: 410
  entry_rate: 1.
  seed_duration: 10.
  contact_rate_multiplier: 2.45 # LSHTM's estimate

  start_time_second_VoC: 562 #15 July 2021
  entry_rate_second_VoC: 1.
  seed_duration_second_VoC: 10.
  contact_rate_multiplier_second_VoC: 3.5