description: BASELINE

country:
  iso3: IDN

mixing_matrices:
  source_iso3: CHN

population:
  region: Bali
  year: 2010

infectious_seed: 250.

waning_immunity_duration: 240.

time:
  start: 220
  end: 1100

mobility:
  microdistancing:
    behaviour:
      function_type: tanh
      parameters:
        shape: .004
        inflection_time: 460
        start_asymptote: 0.
        end_asymptote: 0.25
      locations:
        - other_locations
        - school
        - work
        - home
  mixing:
    school:
      append: false
      times:
        - 2020-03-13
        - 2020-03-14  # Jakarta suspends schools
        - 2020-03-23
        - 2020-03-24  # Schools suspended nationwide
      values:
        - 1.
        - 0.96  # Assuming Jakarta is 4% of Indonesia's population
        - 0.96
        - 0.

testing_to_detection:
  assumed_tests_parameter: 1.e-04
  assumed_cdr_parameter: 0.0004
  smoothing_period: 14

contact_tracing:
  assumed_trace_prop: 0.02
  assumed_prev: 1.e-3
  quarantine_infect_multiplier: 0.2
  floor: 0.

voc_emergence:
  delta:
    start_time: 400
    entry_rate: 1.
    seed_duration: 10.

vaccination:
  one_dose:
    ve_sympt_covid: 0.6
    ve_prop_prevent_infection: 0.65
    ve_infectiousness: 0.5
  roll_out_components:
    - supply_period_coverage:
        coverage: 0.54
        start_time: 398
        end_time: 579
      age_min: 20
      age_max: 50
