description: BASELINE

country:
  iso3: IDN

population:
  region: Bali
  year: 2010

infectious_seed: 250.

stratify_by_infection_history: true
waning_immunity_duration: 240.

time:
  start: 240
  end: 700

mobility:
  google_mobility_locations:  # Not mapping residential mobility to home
    work:
      - workplaces
    other_locations:
      - retail_and_recreation
      - grocery_and_pharmacy
      - parks
      - transit_stations
  microdistancing:
    behaviour:
      function_type: tanh
      parameters:
        shape: .004
        inflection_time: 460
        lower_asymptote: 0.
        upper_asymptote: 0.25
      locations:
        - other_locations
        - school
        - work
        - home
  mixing:
    school:
      append: false
      times:
        - 2020-03-13
        - 2020-03-14  # Jakarta suspends schools
        - 2020-03-23
        - 2020-03-24  # Schools suspended nationwide
      values:
        - 1.
        - 0.96  # Assuming Jakarta is 4% of Indonesia's population
        - 0.96
        - 0.

testing_to_detection:
  assumed_tests_parameter: 1.e-04
  assumed_cdr_parameter: 0.04
  smoothing_period: 14

contact_tracing:
  assumed_trace_prop: 0.2
  assumed_prev: 1.e-3
  quarantine_infect_multiplier: 0.2

voc_emergence:
  delta:
    start_time: 500
    entry_rate: 1.
    seed_duration: 10.

vaccination:
  overall_efficacy: 0.6
  vacc_prop_prevent_infection: 0.65
  vacc_reduce_infectiousness: 0.5
  roll_out_components:
    - supply_period_coverage:
        coverage: 0.444
        start_time: 398
        end_time: 579
      age_min: 20
      age_max: 50
