descriptions:
  contact_rate: "Rate of effective contacts"
  infectious_period: "Infectious period"
  cdr: "Case detection rate (proportion of infections captured through surveillance)"
  ba2_rel_infness: "Relative infectiousness of BA.2 relative to BA.1"
units:
  contact_rate: "contacts per person per day"
  infectious_period: "days"
  cdr: ""
  ba2_rel_infness: ""
evidence:
  contact_rate: "Calibrated within plausible range"
  infectious_period: "This quantity is difficult to estimate, given that identified cases are typically quarantined. Studies in settings of high case ascertainment and an effective public health response have suggested a duration of greater than 5.5 days \\cite{bi2020}. PCR positivity, which may continue for up to two to three weeks from the point of symptom onset \\cite{he2020} \\cite{byrne2020} does not necessarily indicate infectiousness. The duration infectious for asymptomatic persons has also been estimated at 6.5 to 9.5 days \\cite{byrne2020}."
  cdr: "Assumed"
  ba2_rel_infness: "Assumed"
