---
parent: null
# Base parameters for the tuberculosis_strains model.

# Parameters used to build a general model of tuberculosis
time:
  start: 1850.
  end: 1851.
  step: 1
  critical_ranges: []

# Country characteristics
iso3: null
region: null

# requested outputs
calculated_outputs: ["prevalence_infectious"]
outputs_stratification: {}
cumulative_output_start_time: 2020.

# model structure
# stratifications by 'age' and by 'organ' are pre-defined but they must be requested to be activated
# other stratifications can be requested as "user_defined_stratifications"
age_breakpoints: ["0", "5", "15"]


# vaccination
bcg:
  coverage: 0.99
  start_time: 1980
  rr_infection_vaccinated: 0.5

# initial conditions
initial_infectious_population: 0
initial_detected_population: 0

# demographics
start_population_size: 500
universal_death_rate: .014

crude_birth_rate: 0.2

# basic infection and disease parameters
contact_rate: 35
rr_infection_latent: 0.4
rr_infection_recovered: 0.4



# latency-related parameters
preventive_treatment_rate: 1.0
preventive_treatment_rate_stratified:
  strain:
    ds: 1.0
    mdr: 0.0


stabilisation_rate: 3.65
stabilisation_rate_stratified:
  age:
    age_0: 1.2
    age_5: 1.2
    age_15: 0.54

early_activation_rate: 0.402
early_activation_rate_stratified:
  age:
    age_0: 6.0
    age_5: 2.45
    age_15: 0.246

late_activation_rate: 0.0020075
late_activation_rate_stratified:
  age:
    age_0: 3.456912e-6
    age_5: 1.164433
    age_15: 0.600411



# active-disease parameters

organ:
  sp_prop: 0.52
  sn_prop: 0.33
  e_prop: 0.15

  sp_foi: 1.0
  sn_foi: 0.24
  e_foi: 0.24

retention_prop: 0.8


self_recovery_rate: 0.2
self_recovery_rate_stratified:
  organ:
    sp: 1.155
    sn: 0.65
    e: 0.65

treatment_duration: 0.5
treatment_duration_stratified:
  strain:
    ds: 1.0
    mdr: 1.5

treatment_success_prop: 0.92
treatment_success_prop_stratified:
  strain:
    ds: 1.0
    mdr: 0.5435

treatment_mortality_prop: 0.024
treatment_mortality_prop_stratified:
  strain:
    ds: 1.0
    mdr: 8.33

treatment_default_prop: 0.056
treatment_default_prop_stratified:
  strain:
    ds: 1.0
    mdr: 5.357


treatment_recovery_rate_stratified:
  strain:
    ds:
    mdr:

treatment_death_rate_stratified:
  strain:
    ds:
    mdr:

treatment_default_rate_stratified:
  strain:
    ds:
    mdr:
  classified:
    correctly:
    incorrectly:

proportion_mdr_misdiagnosed_as_ds_transition_to_fail_lost: 0.1

amplification_prob: 0.07

spontaneous_recovery_rate: 0.2
spontaneous_recovery_rate_stratified:
  strain:
    ds: 0.0
    mdr: 1.0
  classified:
    correctly: 0.0
    incorrectly: 1.0

failure_retreatment_rate: 0.4
failure_retreatment_rate_stratified:
  strain:
    ds: 0.0
    mdr: 1.0
  classified:
    correctly: 0.0
    incorrectly: 1.0
  retention:
    yes: 1.0
    no: 0.0

# treatment_recovery_rate: 1.84
relapse_rate: 0.11
#detection_rate: 5.0

case_detection_prop: 0.62
case_detection_prop_sp: 0.62
frontline_xpert_prop: 0.07


detection_rate_stratified:
  organ:
    sp: 1.0



treatment_commencement_rate: 26
treatment_commencement_rate_stratified:
  strain:
    ds: 1.0
    mdr: 0.5

missed_to_active_rate: 4

# death rates
infect_death_rate: 0.7
infect_death_rate_stratified:
  organ:
    sp: 1.0
    sn: 0.4142857
    e: 0.4142857

natural_recovery_rate: 0.231
natural_recovery_rate_stratified:
  organ:
    sp: 1.0
    sn: 0.563
    e: 0.563

treatment_death_rate: 0.05




extra_params: {} # used to add parameters used for specific applications


# Multiplier scaling the covariance matrix in the Haario Metropolis. 2.4 is the value recommended by Haario.
haario_scaling_factor: 2.4  # Greater values increase jumping step size and reduce the acceptance ratio

