---
parent: null
# Base parameters for the tuberculosis_strains model.

# Parameters used to build a general model of tuberculosis
time:
  start: 1900.
  end: 2020.
  step: 1
  critical_ranges: []

# Country caracteristics
iso3: null
region: null

# requested outputs
calculated_outputs: ["prevalence_infectious"]
outputs_stratification: {}
cumulative_output_start_time: 2020.

# model structure
# stratifications by 'age' and by 'organ' are pre-defined but they must be requested to be activated
# other stratifications can be requested as "user_defined_stratifications"

# initial conditions
initial_infectious_population: 100

# demographics
start_population_size: 500
universal_death_rate: .014

crude_birth_rate: 5.0

# basic infection and disease parameters
contact_rate: 1.4
rr_infection_latent: 0.21
rr_infection_recovered: 1.0


# latency-related parameters
stabilisation_rate: 1.0e-2
late_activation_rate: 5.5e-6
early_activation_rate: 1.1e-3

# active-disease parameters
self_recovery_rate: 0.2
treatment_recovery_rate: 2.0
relapse_rate: 0.1
detection_rate: 5.0

# death rates
infect_death_rate: 0.2
treatment_death_rate: 0.02



extra_params: {} # used to add parameters used for specific applications


# Multiplier scaling the covariance matrix in the Haario Metropolis. 2.4 is the value recommended by Haario.
haario_scaling_factor: 2.4  # Greater values increase jumping step size and reduce the acceptance ratio

