---
parent: null
# Base parameters for the tuberculosis_strains model.

# Parameters used to build a general model of tuberculosis
time:
  start: 1850.
  end: 2020.
  step: 1
  critical_ranges: []

# Country caracteristics
iso3: null
region: null

# requested outputs
calculated_outputs: ["prevalence_infectious"]
outputs_stratification: {}
cumulative_output_start_time: 2020.

# model structure
# stratifications by 'age' and by 'organ' are pre-defined but they must be requested to be activated
# other stratifications can be requested as "user_defined_stratifications"
age_breakpoints: ["0", "5", "15"]


# vaccination
bcg:
  coverage: 0.95
  start_time: 1980
  rr_infection_vaccinated: 0.05

# initial conditions
initial_infectious_population: 0
initial_detected_population: 0

# demographics
start_population_size: 500
universal_death_rate: .014

crude_birth_rate: 0.2

# basic infection and disease parameters
contact_rate: 14.0
rr_infection_latent: 0.4
rr_infection_recovered: 1.0


# latency-related parameters
stabilisation_rate: 3.65
stabilisation_rate_stratified:
  age_0: 1.2
  age_5: 1.2
  age_15: 0.54
late_activation_rate: 0.002
late_activation_rate_stratified:
  age:
    age_0: 3.46e-6
    age_5: 1.16
    age_15: 0.6



early_activation_rate: 2.2e-3

# active-disease parameters

organ:
  sp_prop: 0.55
  sn_prop: 0.25
  e_prop: 0.20

  sp_foi: 1.0
  sn_foi: 0.24
  e_foi: 0.24


self_recovery_rate: 0.2
treatment_recovery_rate: 1.84
relapse_rate: 0.11
#detection_rate: 5.0

case_detection_prop: 0.62
case_detection_prop_sp: 0.85
frontline_xpert_prop: 0.03


detection_rate_stratified:
  organ:
    sp: 1.0

retention_rate: 0.8

treatment_commencement_rate: 26
treatment_commencement_rate_stratified:
  strain:
    ds: 1.0
    mdr: 0.5

missed_to_active_rate: 4

# death rates
infect_death_rate: 0.7

infect_death_rate_stratified:
  organ:
    sp: 1.0
    sn: 0.414
    e: 0.414

natural_recovery_rate: 0.231
natural_recovery_rate_stratified:
  organ:
    sp: 1.0
    sn: 0.563
    e: 0.563

treatment_death_rate: 0.05



extra_params: {} # used to add parameters used for specific applications


# Multiplier scaling the covariance matrix in the Haario Metropolis. 2.4 is the value recommended by Haario.
haario_scaling_factor: 2.4  # Greater values increase jumping step size and reduce the acceptance ratio

