description: BASELINE

country:
  iso3: ITA

mobility:
  mixing:
    school:
      append: false
      times:
        - 2020-03-09
        - 2020-03-10
        - 2020-09-13
        - 2020-09-15
      values:
        - 1.0
        - 0.1
        - 0.1
        - 1.

infectious_seed: 200
contact_rate: 0.04
