description: BASELINE

population:
  region: Metro Manila

mixing_matrices:  # spectral radius of extrapolated all-locations contact matrix 2.3 times smaller than that of the Prem matrix
  type: extrapolated
  source_iso3: HKG

mobility:
  region: Metro Manila
  microdistancing:
    behaviour:
      parameters:
        times:
          - 200
          - 210
          - 240
          - 300
          - 400
          - 430
          - 440
          - 450
          - 530
          - 550
          - 584 # ECQ starts
          - 586
        values:
          - .1  # 200
          - 1   # 210
          - 1   # 240
          - .7  # 300
          - .3  # 400
          - .1  # 430
          - .8  # 440
          - 1.  # 450
          - 1.  # 530
          - 0.4  # 550
          - 0.4  # 484
          - 0.6  # 486
