description: BASELINE

population:
  region: Metro Manila

mobility:
  region: Metro Manila
  mixing:
    other_locations:
      append: true
      times:
        - 2021-08-20
        - 2021-08-22
      values:
        - - ECQ
          - other_locations
        - - MECQ
          - other_locations
    work:
      append: true
      times:
        - 2021-08-20
        - 2021-08-22
      values:
        - - ECQ
          - work
        - - MECQ
          - work
  microdistancing:
    behaviour:
      parameters:
        times:
          - 200
          - 210
          - 240
          - 300
          - 400
          - 430
          - 440
          - 450
          - 530
          - 550
          - 584 # ECQ starts
          - 586
        values:
          - .1  # 200
          - 1   # 210
          - 1   # 240
          - .7  # 300
          - .3  # 400
          - .1  # 430
          - .8  # 440
          - 1.  # 450
          - 1.  # 530
          - 0.4  # 550
          - 0.4  # 484
          - 0.6  # 486
