description: BASELINE

contact_rate: 0.027

time:
  start: 250

population:
  region: Selangor
  year: 2019

mobility:
  microdistancing:
    behaviour:
      parameters:
        upper_asymptote: 0.2
