description: BASELINE

country:
  iso3: FRA

ref_mixing_iso3: BEL

mobility:
  mixing:
    school:
      append: false
      times:
        - 2020-03-15
        - 2020-03-16
        - 2020-09-01
        - 2020-09-03
      values:
        - 1.0
        - 0.1
        - 0.1
        - 1.0

infectious_seed: 300
contact_rate: 0.042
