description: BASELINE

contact_rate: 0.0231
infectious_seed: 100.

time:
  start: 180
  end: 850

country:
  iso3: MYS

clinical_stratification:
  non_sympt_infect_multiplier: 0.25
  props:
    symptomatic:
      multiplier: 1.5

vaccination:
  overall_efficacy: 0.7
  vacc_prop_prevent_infection: 1
  roll_out_components:
    - supply_period_coverage:
        coverage: .06
        start_time: 481 # 25 Apr 2021
        end_time: 569 # 23 July 2021
    - supply_period_coverage:
        coverage: .80
        start_time: 569 # 23 July 2021
        end_time: 755 # 23 Jan 2022


testing_to_detection:
  assumed_tests_parameter: 1.e-04
  assumed_cdr_parameter: 0.06
  smoothing_period: 14

mobility:
  microdistancing:
    behaviour:
      function_type: tanh
      parameters:
        shape: .1
        inflection_time: 398. # 1st February 2021
        lower_asymptote: 0.
        upper_asymptote: 0.11
      locations:
        - other_locations
        - school
        - work
        - home
  mixing:
    school:
      append: false
      times:
        - 2020-03-16 # All schools close
        - 2020-03-17
        - 2020-06-24 # Secondary exam years
        - 2020-06-25
        - 2020-07-15 # Primary exam years
        - 2020-07-16
        - 2020-07-22 # Schools reopen
        - 2020-07-23
        - 2020-10-13 # Schools partially close again
        - 2020-10-14
        - 2020-11-08 # Schools fully close again
        - 2020-11-09
        - 2021-03-06 # All but high schools re-open
        - 2021-03-07
        - 2021-04-03 # Full school re-openings
        - 2021-04-04
        - 2021-05-01
        - 2021-05-02 # Schools fully close again
      values:
        - 1.
        - 0.
        - 0.
        - 0.2
        - 0.2
        - 0.35
        - 0.35
        - 1.
        - 1.
        - 0.64
        - 0.64
        - 0.
        - 0.
        - 0.5
        - 0.5
        - 1.
        - 1.
        - 0.


voc_emergence:
  voc_strain:
    - voc_components:
        start_time: 381 #15 Jan 2021
        entry_rate: 1.
        seed_duration: 10.
        contact_rate_multiplier: 1.56

    - voc_components: #second voc strain
        start_time: 532
        entry_rate: 1.
        seed_duration: 10.
        contact_rate_multiplier: 2.56

contact_tracing:
    assumed_trace_prop: 0.05
    assumed_prev: 1.e-3
    quarantine_infect_multiplier: 0.2