description: BASELINE
parent: apps/covid_19/params.yml

contact_rate: 0.0195
seasonal_force: -0.2
infectious_seed: 100.

time:
  start: 210.
  end: 400.

country:
  iso3: MYS

testing_to_detection:
  assumed_tests_parameter: 1.e-04
  assumed_cdr_parameter: 0.4
  smoothing_period: 14

mobility:
  microdistancing:
    behaviour:
      function_type: tanh
      parameters:
        b: .05
        c: 300.
        sigma: 0.
        upper_asymptote: 0.15
  mixing:
    school:
      append: false
      times:
        - 2020-03-16 # All schools close
        - 2020-03-17
        - 2020-06-24 # Secondary exam years
        - 2020-06-25
        - 2020-07-15 # Primary exam years
        - 2020-07-16
        - 2020-07-22 # Schools reopen
        - 2020-07-23
        - 2020-10-13 # Schools partially close again
        - 2020-10-14
        - 2020-11-08 # Schools fully close again
        - 2020-11-09
      values:
        - 1.
        - 0.
        - 0.
        - 0.2
        - 0.2
        - 0.35
        - 0.35
        - 1.
        - 1.
        - 0.64
        - 0.64
        - 0.

importation: null
