# SCENARIO DESCRIPTION: BASELINE
---
parent: apps/covid_19/params.yml
iso3: MYS
implement_importation: True

start_time: 60.

traveller_quarantine:
  times:
    - 72.
    - 73.  # Self-isolation from 13 March
    - 91.
    - 92.  # Quarantine centres from 1st April
    - 161.
    - 162.  # Back to home quarantine 10th June
    - 175.
    - 176.  # Back to quarantine centres from 24th July
  values:
    - 0.0
    - 0.5  # Self-isolation from 13 March
    - 0.5
    - 0.8  # Quarantine centres from 1st April
    - 0.8
    - 0.5  # Back to home quarantine 10th June
    - 0.5
    - 0.8  # Back to quarantine centres from 24th July

contact_rate: 0.02

testing_to_detection:
  assumed_tests_parameter: 1.e-04
  assumed_cdr_parameter: 0.4

microdistancing:
  function_type: empiric
  parameters:
    max_effect: 0.6
    times:
      - 77
      - 78
      - 133
      - 134
      - 161
      - 162

    values:
      - 0.
      - 1.  # MCO starts (18th March)
      - 1.
      - 0.85  # CMCO starts (12th May)
      - 0.85
      - 0.7  # RMCO starts (10th June)

mixing:
  school:
    append: false
    times:
      - 2020-03-16  # All schools close
      - 2020-03-17
      - 2020-06-24  # Secondary exam years
      - 2020-06-25
      - 2020-07-15  # Primary exam years
      - 2020-07-16
      - 2020-07-22  # Schools reopen
      - 2020-07-23
      - 2020-08-27  # Not sure why I need this, but the code crashes without it
    values:
      - 1.
      - 0.
      - 0.
      - 0.2
      - 0.2
      - 0.35
      - 0.35
      - 1.
      - 1.

data: # Daily numbers of reported imported cases. (two different approaches here)
  times_imported_cases:
    [
      120,
      121,
      122,
      123,
      124,
      125,
      126,
      127,
      128,
      129,
      130,
      131,
      132,
      133,
      134,
      135,
      136,
      137,
      138,
      139,
      140,
      141,
      142,
      143,
      144,
      145,
      146,
      147,
      148,
      149,
      150,
      151,
      152,
      153,
      154,
      155,
      156,
      157,
      158,
      159,
      160,
      161,
      162,
      163,
      164,
      165,
      166,
      167,
      168,
      169,
      170,
      171,
      172,
      173,
      174,
      175,
      176,
      177,
      178,
      179,
      180,
      181,
      182,
      183,
      184,
      185,
      186,
      187,
      188,
      189,
      190,
      191,
      192,
      193,
      194,
      195,
      196,
      197,
      198,
      199,
      200,
      201,
      202,
      203,
      204,
      205,
      206,
      207,
      208,
      209,
      210,
      211,
      212,
      213,
      214,
      215,
      216,
      217,
      218,
      219,
      220,
      221,
      222,
      223,
      224,
      225,
      226,
      227,
      228,
      229,
      230,
      231,
      232,
      233,
      234,
      235,
      236,
      237,
      238,
      239,
      240,
      241,
      242,
      243,
    ]
  n_imported_cases:
    [
      72,
      25,
      12,
      11,
      52,
      7,
      0,
      1,
      1,
      4,
      1,
      0,
      13,
      3,
      4,
      0,
      0,
      6,
      5,
      21,
      2,
      10,
      3,
      25,
      4,
      7,
      5,
      10,
      6,
      0,
      7,
      3,
      10,
      26,
      15,
      0,
      2,
      7,
      8,
      6,
      2,
      6,
      1,
      11,
      16,
      5,
      2,
      3,
      1,
      0,
      3,
      2,
      2,
      3,
      2,
      0,
      2,
      3,
      5,
      4,
      4,
      1,
      1,
      1,
      1,
      3,
      7,
      3,
      3,
      4,
      3,
      6,
      8,
      4,
      3,
      6,
      4,
      1,
      1,
      10,
      4,
      4,
      6,
      4,
      8,
      3,
      5,
      6,
      3,
      4,
      11,
      8,
      3,
      5,
      7,
      1,
      0,
      0,
      15,
      5,
      9,
      6,
      9,
      5,
      5,
      8,
      4,
      7,
      3,
      16,
      2,
      4,
      4,
      5,
      4,
      3,
      8,
      2,
      2,
      1,
      2,
      8,
      10,
      15,
    ]

importation_props_by_age:
  "0": 0.06
  "5": 0.06
  "10": 0.06
  "15": 0.06
  "20": 0.06
  "25": 0.07
  "30": 0.07
  "35": 0.07
  "40": 0.07
  "45": 0.06
  "50": 0.06
  "55": 0.06
  "60": 0.06
  "65": 0.06
  "70": 0.06
  "75": 0.06
