description: BASELINE

country:
  iso3: SWE

ref_mixing_iso3: FIN

mobility:
  mixing:
    school:
      append: false
      times:
        - 2020-08-25 # google mobility data update, pls review
      values:
        - 1.0

infectious_seed: 100
contact_rate: 0.03
