description: BASELINE

population:
  region: Calabarzon

mixing_matrices:  # spectral radius of extrapolated all-locations contact matrix 2.3 times smaller than that of the Prem matrix
  source_iso3: HKG

mobility:
  region: Calabarzon
  google_mobility_locations:
    work:
      - workplaces
    other_locations:
      - retail_and_recreation
      - grocery_and_pharmacy
      - transit_stations
  microdistancing:
    behaviour:
      parameters:
        times:
          - 200
          - 220
          - 450
          - 460
          - 470
          - 475
        values:
          - 0.2
          - 0.7
          - 0.7
          - 0.5
          - 0.5
          - 1.
voc_emergence:
  alpha_beta:
    start_time: 400
    entry_rate: 5.
    seed_duration: 10.
    contact_rate_multiplier: 1.5
  delta:
    start_time: 550
    entry_rate: 10.
    seed_duration: 10.
    contact_rate_multiplier: 2.5

# Vaccination-related
vaccination:
  roll_out_components:
    - age_min: 20  # the 20+ age group covers 62.1% of the total Calabarzon population
      supply_period_coverage:
        coverage: .24  # calculated such that 15% of the total Calabarzon population is fully vaccinated by 18 Sep
        start_time: 426 # 1 Mar 2021
        end_time: 627 # 18 Sep 2021
    - age_min: 20
      supply_period_coverage:
        coverage: .34  #to reach 50% of 20+ fully-vaccinated by end of year 2021
        start_time: 627 # 18 Sep 2021
        end_time: 731 # 31 Dec 2021
