function[flowsmat]=compartmentflows(sa,sb,sc,las,lbs,ise,isz,isp,...
    dwse,dwsz,dwsp,ddse,ddsz,ddsp,tise,tisz,tisp,tnse,tnsz,tnsp,...
    lam,lbm,ime,imz,imp,dwme,dwmz,dwmp,dxme,dxmz,dxmp,time,timz,timp,...
    ddme,ddmz,ddmp,tnme,tnmz,tnmp,lambdas,lambdam,lambdads,lambdadm,...
    xis,xim,kappa,gammaez,gammaxez,gammaxp,gammap,nue,nuz,nup,...
    epse,epsz,epsp,eta,omegatis,omegatns,omegatim,omegatnm,...
    omicron,deltase,deltasz,deltasp,deltame,deltamz,deltamp,...
    deltaxme,deltaxmz,deltaxmp,deltaseinc,deltaszinc,deltaspinc,...
    taui,taus,taum,upsilons,upsilonm,sigmas,sigmam,...
    mu,muez,muxez,mup,muxp,mutis,mutns,mutim,mutnm,...
    ppv,suspecttocaseratio,suspecttocaseratioipt,labdst,xpertprop)

%DEFINE THE FLOWS BETWEEN COMPARTMENTS
flowsmat=...
    [-(lambdas+lambdam+mu).*sa;... %1. sa
    -(lambdads+lambdadm+mu).*sb;... %2. sb
    xis.*(tnse+tnsz+tnsp)+xim.*(tnme+tnmz+tnmp)-(lambdads+lambdadm+mu).*sc;... %3. sc
    lambdas.*sa+lambdads.*(sb+sc+lbs+lbm)-(epse+epsz+epsp+kappa+mu).*las;... %4. las
    kappa.*las+gammaez.*(ise+ddse+isz+ddsz)+gammap.*(isp+ddsp)-...
    (lambdads+lambdadm+nue+nuz+nup+mu).*lbs;... %5. lbs
    epse.*las+nue.*lbs+....
    (1-eta).*(omegatis.*tise+omegatns.*tnse)+...
    omicron.*ddse-(deltase+gammaez+muez).*ise;... %6. ise
    epsz.*las+nuz.*lbs+...
    (1-eta).*(omegatis.*tisz+omegatns.*tnsz)+...
    omicron.*ddsz-(deltasz+gammaez+muez).*isz;... %7. isz
    epsp.*las+nup.*lbs+...
    (1-eta).*(omegatis.*tisp+omegatns.*tnsp)+...
    omicron.*ddsp-(deltasp+gammap+mup).*isp;... %8. isp
    deltase.*ise-(sigmas+muez).*dwse;... %9. dwse
    deltasz.*isz-(sigmas+muez).*dwsz;... %10. dwsz
    deltasp.*isp-(sigmas+mup).*dwsp;... %11. dwsp
    upsilons.*sigmas.*dwse-(omicron+gammaez+muez).*ddse;... %12. ddse
    upsilons.*sigmas.*dwsz-(omicron+gammaez+muez).*ddsz;... %13. ddsz
    upsilons.*sigmas.*dwsp-(omicron+gammap+mup).*ddsp;... %14. ddsp
    (1-upsilons).*sigmas.*dwse-(taus+mutis+omegatis).*tise;... %15. tise
    (1-upsilons).*sigmas.*dwsz-(taus+mutis+omegatis).*tisz;... %16. tisz
    (1-upsilons).*sigmas.*dwsp-(taus+mutis+omegatis).*tisp;... %17. tisp
    taus.*tise-(xis+mutns+omegatns).*tnse;... %18. tnse
    taus.*tisz-(xis+mutns+omegatns).*tnsz;... %19. tnsz
    taus.*tisp-(xis+mutns+omegatns).*tnsp;... %20. tnsp
    lambdam.*sa+lambdadm.*(sb+sc+lbs+lbm)-...
    (epse+epsz+epsp+kappa+mu).*lam;... %21. lam
    kappa.*lam+gammaez.*(ime+ddme+imz+ddmz)+...
    gammaxez.*(dxme+dxmz)+...
    gammap.*(imp+ddmp)+gammaxp.*dxmp-...
    (lambdads+lambdadm+nue+nuz+nup+mu).*lbm;... %22. lbm
    epse.*lam+nue.*lbm+taui.*dxme+...
    eta.*(omegatis.*tise+omegatns.*tnse)+...
    omegatim.*time+omegatnm.*tnme+omicron.*ddme-...
    (deltame+deltaxme+gammaez+muez).*ime;... %23. ime
    epsz.*lam+nuz.*lbm+taui.*dxmz+...
    eta.*(omegatis.*tisz+omegatns.*tnsz)+...
    omegatim.*timz+omegatnm.*tnmz+omicron.*ddmz-...
    (deltamz+deltaxmz+gammaez+muez).*imz;... %24. imz
    epsp.*lam+nup.*lbm+taui.*dxmp+...
    eta.*(omegatis.*tisp+omegatns.*tnsp)+...
    omegatim.*timp+omegatnm.*tnmp+omicron.*ddmp-...
    (deltamp+deltaxmp+gammap+mup).*imp;... %25. imp
    deltame.*ime-(sigmam+muez).*dwme;... %26. dwme
    deltamz.*imz-(sigmam+muez).*dwmz;... %27. dwmz
    deltamp.*imp-(sigmam+mup).*dwmp;... %28. dwmp
    upsilonm.*sigmam.*dwme-(omicron+gammaez+muez).*ddme;... %29. ddme
    upsilonm.*sigmam.*dwmz-(omicron+gammaez+muez).*ddmz;... %30. ddmz
    upsilonm.*sigmam.*dwmp-(omicron+gammap+mup).*ddmp;... %31. ddmp
    deltaxme.*ime-(taui+gammaxez+muxez).*dxme;... %32. dxme
    deltaxmz.*imz-(taui+gammaxez+muxez).*dxmz;... %33. dxmz
    deltaxmp.*imp-(taui+gammaxp+muxp).*dxmp;... %34. dxmp
    (1-upsilonm).*sigmam.*dwme-(taum+mutim+omegatim).*time;... %35. time
    (1-upsilonm).*sigmam.*dwmz-(taum+mutim+omegatim).*timz;... %36. timz
    (1-upsilonm).*sigmam.*dwmp-(taum+mutim+omegatim).*timp;... %37. timp
    taum.*time-(xim+mutnm+omegatnm).*tnme;... %38. tnme
    taum.*timz-(xim+mutnm+omegatnm).*tnmz;... %39. tnmz
    taum.*timp-(xim+mutnm+omegatnm).*tnmp;... %40. tnmp
    lambdas.*sa+lambdads.*(sb+sc+lbs+lbm);... %41. DS annual new infections
    lambdam.*sa+lambdadm.*(sb+sc+lbs+lbm);... %42. MDR annual new infections
    (epse+epsz+epsp).*las;... %43. DS rapid progression incidence
    (epse+epsz+epsp).*lam;... %44. MDR rapid progression incidence
    (nue+nuz+nup).*lbs;... %45. DS reactivation incidence
    (nue+nuz+nup).*lbm;... %46. MDR reactivation incidence
    epse.*(las+lam)+nue.*(lbs+lbm);... %47. Extrapulmonary incidence
    epsz.*(las+lam)+nuz.*(lbs+lbm);... %48. Smear negative incidence
    epsp.*(las+lam)+nup.*(lbs+lbm);... %49. Smear positive incidence
    ((deltase.*ise)+(deltasz.*isz)+(deltasp.*isp)+...
    (deltaxme.*ime)+(deltaxmz.*imz)+(deltaxmp.*imp))/...
    ppv;... %50. DS detections (including FPs)
    ((deltame.*ime)+(deltamz.*imz)+(deltamp.*imp))/...
    ppv;... %51. MDR detections (including FPs)
    (1-upsilons).*sigmas.*(dwse+dwsz+dwsp)/ppv;... %52. DS commence treatment
    (1-upsilonm).*sigmam.*(dwme+dwmz+dwmp)/ppv;... %53. MDR commence treatment
    muez.*(ise+dwse+ddse+isz+dwsz+ddsz)+mup.*(isp+dwsp+ddsp)+...
    mutis.*(tise+tisz+tisp)+mutns.*(tnse+tnsz+tnsp);... %54. DS deaths
    muez.*(ime+dwme+ddme)+muez.*(imz+dwmz+ddmz)+mup.*(imp+dwmp+ddmp)+...
    muxez.*(dxme+dxmz)+muxp.*dxmp+mutim.*(time+timz+timp)+...
    mutnm.*(tnme+tnmz+tnmp);... %55. MDR deaths
    mu.*(sa+sb+sc+las+lbs+lam+lbm);... %56. Non-TB deaths
    (deltase.*(ise+ime)+deltasz.*(isz+imz)+deltasp.*(isp+imp)).*...
    labdst/ppv*suspecttocaseratio;... %57. DSTs done
    gammaez.*(ddse+ddsz)+gammap.*(ddsp)+...
    (1-eta).*(omegatis.*(tise+tisz+tisp)+omegatns.*(tnse+tnsz+tnsp))+...
    omicron.*(ddse+ddsz+ddsp);... %58. DS relapses
    gammaez.*(ddme+dxme+ddmz+dxmz)+...
    gammap.*ddmp+gammaxp.*dxmp+...
    taui.*(dxme+dxmz+dxmp)+...
    eta.*(omegatis.*(tise+tisz+tisp)+omegatns.*(tnsz+tnse+tnsp))+...
    omegatim.*(time+timz+timp)+omegatnm.*(tnme+tnmz+tnmp)+...
    omicron.*(ddme+ddmz+ddmp);... %59. MDR relapses
    (deltaseinc.*(ise+ime)+deltaszinc.*(isz+imz)+deltaspinc.*...
    (isp+imp))/ppv;... %60. extra IPT detections    
    (deltaseinc.*(ise+ime)+deltaszinc.*(isz+imz)+deltaspinc.*(isp+imp))/...
    ppv*suspecttocaseratioipt;... %61. IPT suspects
    ((deltase.*ise)+(deltasz.*isz)+(deltasp.*isp)+...
    (deltame+deltaxme).*ime+(deltamz+deltaxmz).*imz+...
    (deltamp+deltaxmp).*imp).*xpertprop/ppv]; %62. GeneXperts
end




