%PARAMETERS OUTPUT MATRIX
function[paramsout]=updateparams(t,Y,access,accessprop,...
    ise,isz,isp,ime,imz,imp,...
    deltase,deltasz,deltasp,deltame,deltamz,deltamp,deltaxme,deltaxmz,...
    deltaxmp,gammaez,gammap,muez,mup,ppv,upsilonm,mdefault,mdeath,...
    iptcoverage,arvlayers)

global country

paramsout=zeros(1,13); %Initiate matrix for one row of parameter outputs
paramsout(1,1)=t; %Record current time
if strcmp(country,'RSA')==1 %Record access to care proportions
    paramsout(1,2)=sum(accessprop(1,1,1:5),3); %
    paramsout(1,3)=sum(accessprop(1,1,6:10),3);
    paramsout(1,4)=sum(accessprop(1,1,11:15),3);
elseif strcmp(country,'China')==1||strcmp(country,'India')==1
    paramsout(1,2)=sum(accessprop(1,1,1),3); %
    paramsout(1,3)=sum(accessprop(1,1,2),3);
    paramsout(1,4)=sum(accessprop(1,1,3),3);
end
if strcmp(country,'RSA')==1
for b=1:access %Weighted average of sojourn times across the untreated
    %infectious compartments and their care access/HIV strata
    paramsout(1,5)=paramsout(1,5)+...
        sum(ise(:,:,b,:),4)/(deltase(1,1,b,1)+gammaez(1,1,b,1)+...
        muez(1,1,b,1))+...
        sum(isz(:,:,b,:),4)/(deltasz(1,1,b,1)+gammaez(1,1,b,1)+...
        muez(1,1,b,1))+...
        sum(isp(:,:,b,:),4)/(deltasp(1,1,b,1)+gammap(1,1,b,1)+...
        mup(1,1,b,1))+...
        sum(ime(:,:,b,:),4)/(deltame(1,1,b,1)+deltaxme(1,1,b,1)+...
        gammaez(1,1,b,1)+muez(1,1,b,1))+...
        sum(imz(:,:,b,:),4)/(deltamz(1,1,b,1)+deltaxmz(1,1,b,1)+...
        gammaez(1,1,b,1)+muez(1,1,b,1))+...
        sum(imp(:,:,b,:),4)/(deltamp(1,1,b,1)+deltaxmp(1,1,b,1)+...
        gammap(1,1,b,1)+mup(1,1,b,1));
end
elseif strcmp(country,'China')==1||strcmp(country,'India')==1
    for b=1:access
        paramsout(1,5)=paramsout(1,5)+...
        sum(ise(:,:,b,:),4)/(deltase(1,1,b,1)+gammaez+muez)+...
        sum(isz(:,:,b,:),4)/(deltasz(1,1,b,1)+gammaez+muez)+...
        sum(isp(:,:,b,:),4)/(deltasp(1,1,b,1)+gammap+mup)+...
        sum(ime(:,:,b,:),4)/(deltame(1,1,b,1)+deltaxme(1,1,b,1)+...
        gammaez+muez)+...
        sum(imz(:,:,b,:),4)/(deltamz(1,1,b,1)+deltaxmz(1,1,b,1)+...
        gammaez+muez)+...
        sum(imp(:,:,b,:),4)/(deltamp(1,1,b,1)+deltaxmp(1,1,b,1)+...
        gammap+mup);
    end
end
paramsout(1,5)=paramsout(1,5)./sum(sum((ise+isz+isp+ime+imz+imp),3),4);
paramsout(1,6)=ppv; %PPV - currently fixed, but can allow to change
paramsout(1,7)=upsilonm(1,1,1,1); %MDR initial default
paramsout(1,8)=1-mdefault(1,1,1,1)-mdeath(1,1,1,1); %MDR default/death
if strcmp(country,'RSA')==1
    paramsout(1,9)=iptcoverage*sum(sum(sum(Y([6:8,23:35],...
        1,arvlayers,:),1),3),4); %IPT coverage numbers
    paramsout(1,10)=iptcoverage; %IPT coerage proportion
    %         save paramsout(1,11) for ACF detections
    %         save paramsout(1,12) for LTBI screens
    %         save parmasout(1,13) for LTBI detections
end

end