description: BASELINE
parent: apps/covid_19/regions/malaysia/params/default.yml

contact_rate: 0.0295

time:
  start: 280

population:
  region: Kuala Lumpur
  year: 2019

mobility:
  microdistancing:
    behaviour:
      parameters:
        upper_asymptote: 0.32


voc_emergence:
  start_time: 381   #15 Jan 2021
  entry_rate: 1.
  seed_duration: 1.
  contact_rate_multiplier: 1.56  # LSHTM's estimate