description: BASELINE
parent: apps/covid_19/regions/malaysia/params/default.yml

contact_rate: 0.045

time:
  start: 300

population:
  region: Kuala Lumpur
  year: 2019

mobility:
  microdistancing:
    behaviour:
      parameters:
        upper_asymptote: 0.3
        inflection_time: 365.
