description: BASELINE
parent: apps/covid_19/regions/malaysia/params/default.yml

contact_rate: 0.0295

time:
  start: 280

population:
  region: Kuala Lumpur
  year: 2019

mobility:
  microdistancing:
    behaviour:
      parameters:
        upper_asymptote: 0.32
