---
# Parameters for the Vietnam model
time:
  start: 1900.0
  end: 2035.0
  step: 1.0

compartments:
    - susceptible
    - early_latent
    - late_latent
    - infectious
    - recovered

population:
  total: 3000000
  compartments:
    infectious: 1000
    late_latent: 1000000

# Model definition parameters
model:
  contact_rate: 14.0
  rr_transmission_recovered: 1.0
  rr_transmission_infected: 0.21
  recovery: 0.231 # this is for smear-positive TB
  infect_death: 0.389 # this is for smear-positive TB
  universal_death_rate: 0.02
  case_detection: 0.0
  ipt_rate: 0.0
  acf_rate: 0.0
  dr_amplification: 0.0
  crude_birth_rate: 0.02
  
# Parameters used to construct time-varying functions.
rates:
  case_detection_rate_multiplier: 1.0
  
  # FIXME: These organ proprotions are different to the ones used in the organ stratifications
  organ_proportions:
    smearpos: 0.25
    smearneg: 0.40
    extrapul: 0.35

  # Disease duration by organ, based on organ_proportions above
  disease_duration:
    smearpos: 1.6
    smearneg: 5.3
    extrapul: 5.3
    overall: 4.375

  # MDR-TB:
  dr_amplification_prop_among_nonsuccess: 0.20 # based on Cox et al and Bonnet et al
  
  # Diagnostic sensitivity by organ status:
  diagnostic_sensitivity:
    smearpos: 1.0
    smearneg: 0.7
    extrapul: 0.5
      
  # Isoniazid preventive therapy (IPT)
  ipt:
    yield_contact_ct_tstpos_per_detected_tb: 2.0 # expected number of infections traced per index
    ipt_efficacy: 0.75 # based on intention-to-treat
  
  # Treatment improvement (C-DOTS)
  reduction_negative_tx_outcome: 0.0
  
  # Active case finding (ACF) for risk groups
  acf:
    coverage: 0.0
    sensitivity: 0.8
    
  case_detection_rate:
    1950: 0
    1980: 0.1
    1990: 0.15
    2000: 0.2
    2010: 0.3
    2015: 0.33

  treatment_success_rate:
    1950: 0
    1970: 0.2
    1994: 0.6
    2000: 0.85
    2010: 0.87
    2016: 0.9
  
# Parameters for strain-based stratification
strain:
  strata: ['ds', 'mdr']
  mdr_tsr: 0.6
  prop_mdr_detected_as_mdr: 0.5
  infectiousness_adjustments:
    ds: 1.0
    mdr: 1.1
  ipt_switch:
    ds: 1.0
    mdr: 0.0

# Parameters for age-based stratification.
age:
  strata: [0, 5, 15, 60]
  
  # Used to increase adult progression rates due to pollution
  adult_latency_adjustment: 4.0 
  adult_latency_adjustment: 2.894561 # Maximum likelihood estimate
  
  # Children contact tracing coverage
  ipt_ct_coverage:
    '0': 0.17
    '5': 0.0 
    '15': 0.0 
    '60': 0.0
  
# Parameters for organ-based stratification
organ:
  strata:
    - smearpos
    - smearneg
    - extrapul

  proportions:
    smearpos: 0.5
    smearneg: 0.3
    extrapul: 0.2

  infectiousness_adjustments:
    smearpos: 1.0
    smearneg: 0.25
    extrapul: 0.0

  mortality_adjustments:
    smearpos: 1.0
    smearneg: 0.064
    extrapul: 0.064

  recovery_adjustments:
    smearpos: 1.0
    smearneg: 0.56
    extrapul: 0.56


# Parameters for location-based stratification.
location:
  strata:
    - rural_province
    - urban_nonger
    - urban_ger
    - prison

  proportions:
    rural_province: 0.48
    urban_nonger: 0.368
    urban_ger: 0.15
    prison: 0.002

  relative_risk_transmission:
    rural_province: 1
    urban_ger: 3.0
    urban_nonger: 0.8
    prison: 50

  acf_rate:
    rural_province: 0.0
    urban_nonger: 0.0
    urban_ger: 0.0
    prison: 0.0

  mixing_matrix: [
    [0.899, 0.05, 0.05, 0.001],
    [0.049, 0.7, 0.25, 0.001],
    [0.049, 0.25, 0.7, 0.001],
    [0.1, 0.1, 0.1, 0.7]
  ]
