# SCENARIO DESCRIPTION: BASELINE
---
parent: apps/tuberculosis_strains/params.yml
iso3: "PHL"


time:
  start: 1950
  end: 2025
  step: 1
  critical_ranges: []


start_population_size: 2.1e+7

crude_birth_rate: 0.035

initial_early_latent_population: 3000
initial_late_latent_population: 5000000
initial_infectious_population: 30000
initial_on_treatment_population: 0

calculated_outputs:
  [
    "prevalence_infectious",
    "percentage_latent",
    "population_size",
    "notifications",
#    "mortality",  # Was causing a bug, so have removed to get calibration running
    "incidence",
  ]
