---
parent: apps/tuberculosis_strains/params.yml
iso3: "PHL"


calculated_outputs:
  [
    "prevalence_infectious",
    "percentage_latent",
    "population_size",
    "notifications",
    "mortality",
    "incidence",
  ]
