---
parent: apps/tuberculosis_strains/params.yml
iso3: "PHL"


time:
  start: 1850.
  end: 2020.
  step: 1
  critical_ranges: []


start_population_size: 3.3e+6

crude_birth_rate: 0.035

initial_infectious_population: 3.0e4

calculated_outputs:
  [
    "prevalence_infectious",
    "percentage_latent",
    "population_size",
    "notifications",
    "mortality",
    "incidence",
  ]
