description: BASELINE

contact_rate: 0.0295

mixing_matrices:
  source_iso3: HKG

time:
  start: 280

population:
  region: Kuala Lumpur
  year: 2019

mobility:
  microdistancing:
    behaviour:
      parameters:
        upper_asymptote: 0.32
