description: BASELINE

contact_rate: 0.0295

ref_mixing_iso3: HKG

time:
  start: 280

population:
  region: Kuala Lumpur
  year: 2019

mobility:
  microdistancing:
    behaviour:
      parameters:
        end_asymptote: 0.32
