---
iso3: PHL

scenario_start_time: 279
end_time: 365.
ifr_multiplier: 2.28

mixing:
  school:
    append: false
    times:
      - 2020-02-11
      - 2020-03-16
      - 2020-07-07
      - 2020-08-11 # If Google mobility passes this point, please update to one week in the future
    values:
      - 1
      - 0
      - 0
<<<<<<< HEAD:apps/covid_19/params/philippines/default.yml
      - 0 
=======
      - 0
>>>>>>> Restructure COVID app:apps/covid_19/regions/philippines/params/default.yml
