# SCENARIO DESCRIPTION: BASELINE
parent: apps/covid_19/eur_optimisation_params.yml

country:
  iso3: SWE

mobility:
  mixing:
    school:
      append: false
      times:
        - 2020-08-25 # google mobility data update, pls review
      values:
        - 1.0
