---
# Parameters used to build the Marshall Island model.
default:
  start_time: 1900.0
  end_time: 2035.0
  time_step: 0.25
  start_population: 4300

  # Base model definition
  contact_rate: 0.0038
  beta_decay_rate: 0.05
  minimum_tv_beta_multiplier: 0.1
  rr_transmission_recovered: 0.6
  rr_transmission_infected: 0.21
  rr_transmission_ltbi_treated: 0.21
  # 'latency_adjustment': 2.,  # used to modify progression rates during calibration
  self_recovery_rate: 0.231 # this is for smear-positive TB
  tb_mortality_rate: 0.389 # this is for smear-positive TB
  prop_smearpos: 0.5
  cdr_multiplier: 1.5

  # Diagnostic sensitivity by organ status:
  diagnostic_sensitivity_smearpos: 1.0
  diagnostic_sensitivity_smearneg: 0.7
  diagnostic_sensitivity_extrapul: 0.5

  # Adjustments by location and diabetes
  rr_transmission_ebeye: 2.2 # reference majuro
  rr_transmission_otherislands: 1.0 # reference majuro
  rr_progression_diabetic: 3.18 # reference: no_diabetes

  # Case detection adjustment for location
  case_detection_majuro_multiplier: 1.0
  case_detection_ebeye_multiplier: 1.5
  case_detection_otherislands_multiplier: 0.8

  # ACF for intervention groups
  acf_coverage: 0.0
  acf_sensitivity: 0.9
  acf_majuro_switch: 0.0
  acf_ebeye_switch: 0.0
  acf_otherislands_switch: 0.0

  # LTBI ACF for intervention groups
  acf_ltbi_coverage: 0.0
  acf_ltbi_sensitivity: 0.8
  acf_ltbi_efficacy: 0.72 # higher than ipt_efficacy as higher completion rate
  acf_ltbi_majuro_switch: 0.0
  acf_ltbi_ebeye_switch: 0.0
  acf_ltbi_otherislands_switch: 0.0

  # Prevalence adjustment
  over_reporting_prevalence_proportion: 0.20

# When the scenarios start running
scenario_start: 1990

# N.B: Scenario keys have to be integers 1-N, or it'll break downstream dashboards.
scenarios: {}
# # The ACF intervention that they actually did in RMI in 2017/2018
# 1:
#   acf_coverage: 1.0
#   acf_majuro_switch: 1.0
#   acf_ebeye_switch: 1.0
#   acf_otherislands_switch: 0.0
#   acf_ltbi_majuro_switch: 1.0
#   acf_ltbi_ebeye_switch: 0.0
#   acf_ltbi_otherislands_switch: 0.0
