description: BASELINE
parent: apps/covid_19/regions/malaysia/params/default.yml

importation: null
contact_rate: 0.0485

time:
  start: 310.

population:
  region: Johor
  year: 2019

mobility:
  microdistancing:
    behaviour:
      parameters:
        upper_asymptote: 0.3
        inflection_time: 365.
