description: BASELINE

infectious_seed: 80

time:
  start: 50
  end: 731

mixing_matrices:
  source_iso3: CHN

country:
  iso3: NPL

waning_immunity_duration: 240.

testing_to_detection:
  assumed_tests_parameter: 1.e-04
  assumed_cdr_parameter: 0.06
  smoothing_period: 14

contact_tracing:
  assumed_trace_prop: 0.05
  assumed_prev: 1.e-3
  quarantine_infect_multiplier: 0.2
  floor: 0.

mobility:
  mixing:
    school:
      append: false
      times:
        - 2020-09-16
        - 2020-09-17
        - 2021-04-19
        - 2021-04-20
      values:
        - 0.
        - 0.5
        - 0.5
        - 0.
  microdistancing:
    behaviour:
      function_type: tanh
      parameters:
        shape: .1
        inflection_time: 280
        start_asymptote: 0.
        end_asymptote: 0.34
      locations:
        - other_locations
        - school
        - work

voc_emergence:
  delta:
    start_time: 400
    entry_rate: 1.
    seed_duration: 10.

vaccination:
  one_dose:
    ve_sympt_covid: 0.7
    ve_prop_prevent_infection: 0.7
    ve_infectiousness: 0.5
  roll_out_components:
    - supply_period_coverage:
        coverage: 0.224  # "Effective vaccination coverage", allowing first dose to be 60% effective
        start_time: 407  # Start vaccinating from 27/1/21, lagged by 14 days to 10/2/21
        end_time: 594  # Report from 16/8/21, not lagged
