description: BASELINE
parent: apps/covid_19/params.yml

contact_rate: 0.019
infectious_seed: 100

time:
  start: 120
  end: 600

country:
  iso3: NPL

testing_to_detection:
  assumed_tests_parameter: 1.e-04
  assumed_cdr_parameter: 0.06
  smoothing_period: 14

mobility:
  google_mobility_locations:
    work:
      - workplaces
    other_locations:
      - retail_and_recreation
      - grocery_and_pharmacy
      - parks
      - transit_stations
    home:
      - residential
  microdistancing:
    behaviour:
      function_type: tanh
      parameters:
        shape: .1
        inflection_time: 300. # 26th October 2020
        lower_asymptote: 0.
        upper_asymptote: 0.2
      locations:
        - other_locations
        - school
        - work

#voc_emergence:
#  voc_strain:
#    - voc_components:
#        start_time: 400.
#        entry_rate: 1.
#        seed_duration: 10.
#        contact_rate_multiplier: 2.  # LSHTM's estimate
