description: BASELINE
parent: apps/covid_19/params.yml

contact_rate: 0.018
infectious_seed: 200.

time:
  start: 0
  end: 822

country:
  iso3: NPL

clinical_stratification:
  non_sympt_infect_multiplier: 0.25
  props:
    symptomatic:
      multiplier: 1.5

vaccination:
  overall_efficacy: 0.75
  vacc_prop_prevent_infection: 1

testing_to_detection:
  assumed_tests_parameter: 1.e-04
  assumed_cdr_parameter: 0.06
  smoothing_period: 14

voc_emergence:
  voc_strain:
    - voc_components:
        start_time: 400.
        entry_rate: 1.
        seed_duration: 10.
        contact_rate_multiplier: 2.3  # LSHTM's estimate
