# SCENARIO DESCRIPTION: BASELINE
---
parent: apps/covid_19/vic_submodel_params.yml

population:
  region: Victoria
  year: 2020

mobility:
  region: Victoria

# Cluster stratification.
victorian_clusters:
  # Allows us to adjust contact rate per-cluster when calibrating
  contact_rate_multipliers:
    barwon_south_west: 1
    gippsland: 0
    hume: 0
    loddon_mallee: 0
    grampians: 0
    north_metro: 0
    south_east_metro: 0
    south_metro: 0
    west_metro: 0

importation:
  case_timeseries:
    times: [153, 154]
    values: [1, 0]
