description: BASELINE
parent: apps/covid_19/params.yml

population:
  region: Victoria
country:
  iso3: AUS

metropolis_initialisation_type: "current_params"
metropolis_init_rel_step_size: 0.05

time:
  start: 135 # No longer the 25th May, but moved earlier (14th May) - to help with model calibration
  end: 275 # 1st October

testing_to_detection: # Need to mention these parameters in the Supplement somewhere
  assumed_tests_parameter: 1.e-03
  smoothing_period: 7

# VAHI, 1st July to 30th September
clinical_stratification:
  icu_prop: 0.089
sojourn:
  compartment_periods:
    hospital_late: 11.2
    icu_late: 7.4

# Cluster stratification.
victorian_clusters:
  # *** METRO ***
  metro:
    mobility:
      region: null
      age_mixing: null
      npi_effectiveness: {}
      google_mobility_locations:
        work:
          - workplaces
        other_locations:
          - retail_and_recreation
          - grocery_and_pharmacy
          - parks
          - transit_stations
        home:
          - residential
      smooth_google_data: false # Whether to apply a 7-day moving average
      square_mobility_effect: true
      microdistancing_locations:
        - other_locations
        - school
        - work
        - home
      mixing:
        school:
          append: false
          times:
            - 2020-05-25
            - 2020-05-26 # 400,000 students return
            - 2020-06-08
            - 2020-06-09 # Remaining 618,000 students return
            - 2020-07-08
            - 2020-07-09 # Schools close for stage 3
          values:
            - 0.
            - 0.393 # 26th May
            - 0.393
            - 1. # 9th June
            - 1.
            - 0. # 9th July
      microdistancing:
        behaviour:
          function_type: tanh
          parameters:
            b: .05
            c: 197. # 15th July
            sigma: 0.
            upper_asymptote: 0.3 # Not important as this is calibrated
        face_coverings: # Mandatory face coverings
          function_type: tanh
          parameters:
            b: 0.5
            c: 205. # 23rd July
            sigma: 0.
            upper_asymptote: 0.2 # Not important as this is calibrated

  # *** REGIONAL ***
  regional:
    mobility:
      region: null
      age_mixing: null
      npi_effectiveness: {}
      google_mobility_locations:
        work:
          - workplaces
        other_locations:
          - retail_and_recreation
          - grocery_and_pharmacy
          - parks
          - transit_stations
        home:
          - residential
      smooth_google_data: false # Whether to apply a 7-day moving average
      square_mobility_effect: true
      microdistancing_locations:
        - other_locations
        - school
        - work
        - home
      mixing:
        school:
          append: false
          times:
            - 2020-05-25
            - 2020-05-26 # 400,000 students return
            - 2020-06-08
            - 2020-06-09 # Remaining 618,000 students return
            - 2020-07-08
            - 2020-07-09 # Schools close for stage 3
          values:
            - 0.
            - 0.393 # 26th May
            - 0.393
            - 1. # 9th June
            - 1.
            - 0. # 9th July
      # Regional Victoria clusters microdistancing function
      microdistancing:
        behaviour:
          function_type: tanh
          parameters:
            b: .05
            c: 197. # 15th July
            sigma: 0.
            upper_asymptote: 0.3 # Not important as this is calibrated
        face_coverings:
          function_type: tanh
          parameters:
            b: 0.5
            c: 215. # 2nd August
            sigma: 0.
            upper_asymptote: 0.2 # Not important as this is calibrated
