description: BASELINE

contact_rate: 0.027

time:
  start: 280

mixing_matrices:
  type: extrapolated
  source_iso3: CHN

population:
  region: Penang
  year: 2019

mobility:
  microdistancing:
    behaviour:
      parameters:
        upper_asymptote: 0.2
