description: BASELINE

contact_rate: 0.027

ref_mixing_iso3: HKG

time:
  start: 280

population:
  region: Penang
  year: 2019

mobility:
  microdistancing:
    behaviour:
      parameters:
        end_asymptote: 0.2
