description: BASELINE
parent: apps/covid_19/regions/malaysia/params/default.yml

contact_rate: 0.0302

time:
  start: 250

population:
  region: Selangor
  year: 2019

mobility:
  microdistancing:
    behaviour:
      parameters:
        upper_asymptote: 0.2
