# SCENARIO DESCRIPTION: BASELINE
---
parent: apps/covid_19/regions/malaysia/params/default.yml

importation: null
infectious_seed: 200
contact_rate: 0.13

population:
  region: Sabah
  year: 2019

time:
  start: 50
  end: 300

testing_to_detection:
  assumed_cdr_parameter: 0.2

mobility:
  mixing:
    school:
      append: false
      times:
        - 2020-07-22
        - 2020-07-23
        - 2020-10-13  # Schools partially close again
        - 2020-10-14
      values:
        - 1.
        - 1.
        - 0.
        - 0.
