description: BASELINE

country:
  iso3: AUS

population:
  region: Victoria
  year: 2020

mobility:
  region: Victoria
  age_mixing: null
  smooth_google_data: false
  square_mobility_effect: true
  google_mobility_locations:
    work:
      workplaces: 1.
    other_locations:
      retail_and_recreation: 0.4
      grocery_and_pharmacy: 0.4
      parks: 0.1
      transit_stations: 0.1
    home:
      residential: 1.
  mixing:
    school:
      append: false
      times:
        - 2021-07-15
        - 2021-07-16  # Schools close with lockdown 5
        - 2021-07-26
        - 2021-07-27  # Schools re-open after lockdown 5
        - 2021-08-04
        - 2021-08-05  # Schools close with lockdown 6
        # For these estimates, see Dave's Teams spreadsheet vic_schools_data.xlsx, 9th December
        - 2021-10-10
        - 2021-10-11
        - 2021-10-21
        - 2021-10-22
        - 2021-11-04
        - 2021-11-05

      values:
        - 1.
        - 0.1
        - 0.1
        - 1.
        - 1.
        - 0.1
        - 0.1
        - 0.15
        - 0.15
        - 0.6
        - 0.6
        - 0.85

  microdistancing:
    home_reduction:
      function_type: constant
      parameters:
        effect: 0.206
      locations:
        - home
    behaviour:
      # Parameters of tanh function manually calibrated using notebooks/user/jtrauer/vic_microdistancing.ipynb
      function_type: tanh
      parameters:
        shape: 0.1
        inflection_time: 595.
        start_asymptote: 0.165
        end_asymptote: 0.241
      locations:
        - other_locations
        - school
        - work
    behaviour_adjuster:
      function_type: constant
      parameters:
        effect: 0.3336881545907932  # Median posterior estimate from 2020
      locations:
        - other_locations
        - school
        - work
    face_coverings: # Mandatory face coverings
      function_type: survey
      parameters:
        effect: 1.
      locations:
        - other_locations
        - school
        - work
    face_coverings_adjuster:
      function_type: constant
      parameters:
        effect: 0.15
      locations:
        - other_locations
        - school
        - work

time:
  start: 550
  end: 730

infectious_seed: 50

contact_rate: 0.073

mixing_matrices:
  source_iso3: GBR

infection_fatality:
  multiplier: 2.

clinical_stratification:
  non_sympt_infect_multiplier: 0.509  # Median posterior estimate from 2020

  # Increase severity, more symptomatic persons and greater death rate, to account for Delta versus wild-type
  # https://academic.oup.com/cid/advance-article/doi/10.1093/cid/ciab721/6356459 gives aOR of 1.88
  # News article also links to some of the more important recent studies and pre-prints
  # https://www.cbc.ca/news/health/does-delta-cause-more-severe-covid-19-here-s-what-we-know-and-don-t-1.6153470
  props:

    # Table 1.1 from NNDSS document on cases in Australia to May 2021
    hospital:
      multiplier: 1.5
      props:
        - 0.029  # 0-4
        - 0.029  # 5-9
        - 0.014  # 10-14
        - 0.014  # 15-19
        - 0.030  # 20-24
        - 0.030  # 25-29
        - 0.047  # 30-34
        - 0.047  # 35-39
        - 0.081  # 40-44
        - 0.081  # 45-49
        - 0.128  # 50-54
        - 0.128  # 55-59
        - 0.221  # 60-64
        - 0.221  # 65-69
        - 0.389  # 70-74
        - 0.471  # 75+ - weighted to the observed cases in >75s as (511 / 2 + 652 + 356) / (1344 / 2 + 1230 + 783)

  icu_prop: 0.1875980041535647  # Median posterior estimate from 2020

# VAHI, 1st July to 30th September
sojourn:
  compartment_periods:
    hospital_late: 4.234  # (1.918919 * 74 + 3.542373 * 590 + 6.747826 * 230 + 5 * 2) / (74 + 590 + 230 + 2)
    icu_early: 13.189283389438017  # Need to calculate - pre-ICU hospital period 5.74 - 4.31 = 1.43 seems too short
    icu_late: 4.31  # mean((3.84, 3.96, 4.07, 4.19, 4.31, 4.43, 4.55, 4.67, 4.78))
  compartment_periods_calculated:
    exposed:
      total_period: 3.  # Incubation period shorter for Delta
    active:
      total_period: 6.  # Median posterior estimate from 2020
      proportions:
        early: 0.5
        late: 0.5

contact_tracing:
  assumed_trace_prop: 0.85
  assumed_prev: 1.e-3
  quarantine_infect_multiplier: 0.2
  floor: 0.5

testing_to_detection:
  assumed_tests_parameter: 1.e-03
  assumed_cdr_parameter: 0.09
  smoothing_period: 7

# VE parameters taken from LSHTM's report:
# https://cmmid.github.io/topics/covid19/reports/omicron_england/report_11_dec_2021.pdf
vaccination:
  # Efficacy parameters
  one_dose:
    ve_sympt_covid: 0.57  # LSHTM
    ve_prop_prevent_infection_ratio: 0.9  # Most of the protection against symptomatic Covid is mediated in this way
    ve_infectiousness: 0.145  # LSHTM
    ve_hospitalisation: 0.88  # LSHTM
    ve_death: 0.935  # LSHTM
  fully_vaccinated:
    ve_sympt_covid: 0.73  # LSHTM
    ve_prop_prevent_infection: 0.9  # As for one dose
    ve_infectiousness: 0.32  # LSHTM
    ve_hospitalisation: 0.945  # LSHTM
    ve_death: 0.955  # LSHTM
  part_waned:
    ve_sympt_covid: 0.285  # Half of the protection against symptomatic Covid
    ve_prop_prevent_infection: 0.8
    ve_infectiousness: 0.15
    ve_hospitalisation: 0.84  #
    ve_death: 0.84
  fully_waned:
    ve_sympt_covid: 0.
    ve_prop_prevent_infection: 0.
    ve_infectiousness: 0.
    ve_hospitalisation: 0.5
    ve_death: 0.5
  boosted:
    ve_sympt_covid: 0.94  # LSHTM
    ve_prop_prevent_infection: 0.9  # As for one dose and fully vaccinated
    ve_infectiousness_ratio: 1.  # The same as for the fully vaccinated
    ve_hospitalisation: 0.993  # LSHTM
    ve_death: 0.993  # LSHTM
  boost_delay: 100000.  # Boosting off in the baseline scenario

  # Transition parameters
  second_dose_delay:
    shape: 0.1
    inflection_time: 624.  # Middle of September 2021, so that most scaling occurs during September
    start_asymptote: 43.  # Baseline lag in vaccination curves, 43 days
    end_asymptote: 28.  # Shortened lag from Dept's spreadsheet, 28 days
  lag: 14
  vacc_full_effect_duration: 90.
  vacc_part_effect_duration: 360.

  roll_out_components:
    - vic_supply:
        start_time: 454
        end_time: 830
        time_intervals: 100
        age_breaks:
          - 10
          - 15
          - 30
          - 40
          - 50
          - 60
          - 70
  program_start_time: 550
