description: BASELINE

time:
  start: 550
  end: 730

contact_rate: 0.02

mixing_matrices:
  source_iso3: GBR

clinical_stratification:
  non_sympt_infect_multiplier: 0.509  # Median posterior estimate from 2020

  # Increase severity, more symptomatic persons and greater death rate, to account for Delta versus wild-type
  # https://academic.oup.com/cid/advance-article/doi/10.1093/cid/ciab721/6356459 gives aOR of 1.88
  # News article also links to some of the more important recent studies and pre-prints
  # https://www.cbc.ca/news/health/does-delta-cause-more-severe-covid-19-here-s-what-we-know-and-don-t-1.6153470
  props:

    # Table 1.1 from NNDSS document on cases in Australia to May 2021
    hospital:
      props:
        - 0.029  # 0-4
        - 0.029  # 5-9
        - 0.014  # 10-14
        - 0.014  # 15-19
        - 0.030  # 20-24
        - 0.030  # 25-29
        - 0.047  # 30-34
        - 0.047  # 35-39
        - 0.081  # 40-44
        - 0.081  # 45-49
        - 0.128  # 50-54
        - 0.128  # 55-59
        - 0.221  # 60-64
        - 0.221  # 65-69
        - 0.389  # 70-74
        - 0.471  # 75+ - weighted to the observed cases in >75s as (511 / 2 + 652 + 356) / (1344 / 2 + 1230 + 783)

  icu_prop: 0.1875980041535647  # Median posterior estimate from 2020

contact_tracing:
  assumed_trace_prop: 0.85
  assumed_prev: 1.e-3
  quarantine_infect_multiplier: 0.2
  floor: 0.5

country:
  iso3: AUS

population:
  region: Victoria
  year: 2020

mobility:
  region: Victoria

testing_to_detection:
  assumed_tests_parameter: 1.e-03
  assumed_cdr_parameter: 0.1
  smoothing_period: 7

# VE parameters taken from LSHTM's Autumn–winter scenarios 2021–2022 report - https://tinyurl.com/ve-params
vaccination:
  one_dose:
    ve_sympt_covid: 0.57
    ve_prop_prevent_infection_ratio: 1.
    ve_infectiousness_ratio: 0.469  # 0.15 / 0.32 (ratio of one to two dose) - varied with fully vaccinated parameter
    ve_hospitalisation: 0.88
    ve_death: 0.94
  fully_vaccinated:
    ve_sympt_covid: 0.73
    ve_prop_prevent_infection: 0.95  # Very high proportions (0.51 versus 0.57 or 0.72 versus 0.73) used in calibration
    ve_infectiousness: 0.32  # Calibrated
    ve_hospitalisation: 0.95
    ve_death: 0.96
  second_dose_delay:
    shape: 0.1
    inflection_time: 624.  # Middle of September 2021, so that most scaling occurs during September
    start_asymptote: 43.  # Baseline lag in vaccination curves, 43 days
    end_asymptote: 28.  # Shortened lag from Dept's spreadsheet, 28 days
  lag: 14
  roll_out_components:
    - vic_supply:
        start_time: 454
        end_time: 830
        time_intervals: 100
        age_breaks:
          - 10
          - 15
          - 30
          - 40
          - 50
          - 60
          - 70
  program_start_time: 550
