---
iso3: PHL
region: Bicol

scenario_start_time: 140
end_time: 365.

use_verity_mortality_estimates: False

# calibrated parameters
start_time: 12.
contact_rate: 0.049
tv_detection_c: 150 # inflection point
tv_detection_sigma: 0
prop_detected_among_symptomatic: 0.5

# other country-specific parameters
tv_detection_b: .05 # shape parameter of the tanh-based curve

mixing:
  school:
    append: false
    times:
      - 2020-02-11
      - 2020-03-16
      - 2020-06-27
    values:
      - 1
      - 0
      - 0
