---
iso3: PHL
region: Metro Manila

scenario_start_time: 279
end_time: 365.

mixing:
  school:
    append: false
    times:
      - 2020-02-11
      - 2020-03-16
      - 2020-07-07
      - 2020-08-11 # If Google mobility passes this point, please update to one week in the future
    values:
      - 1.
      - 0.
      - 0
      - 0
