# SCENARIO DESCRIPTION: BASELINE
---
iso3: PHL
region: Metro Manila

scenario_start_time: 279
end_time: 365.
hospital_props_multiplier: 2.

mixing:
  school:
    append: false
    times:
      - 2020-02-11
      - 2020-03-16
      - 2020-07-07
      - 2020-08-25 # If Google mobility passes this point, please update to one week in the future
    values:
      - 1.
      - 0.
      - 0
      - 0

microdistancing:
    function_type: empiric
    parameters:
        multiplier: 0.05
        times: [75, 76, 77, 137, 138, 153, 154, 214, 215, 231]
        values: [0, 5, 5, 4, 4, 3, 3, 4, 4, 2]

    # 16 March, day 76, ECQ enforced for whole region
    # 16 May, day 137, MECQ enforced for whole region
    # 1 June, day 153, GCQ for all regions
    # 1 Aug, day 214, MECQ enforced
    # 15 Aug, day 228, face masks/shields required
    # 18 Aug, day 231, GCQ enforced + face masks/sheilds
    
    # no restrictions = 0
    # face fasks = 1
    # modified general community quarantine (MGCQ) = 2
    # general community quarantine (GCQ) = 3
    # modified enhanced community quarantine (MECQ) = 4
    # enhanced community quarantine (ECQ) = 5