description: BASELINE
parent: apps/covid_19/phl_submodel_params.yml

population:
  region: Metro Manila

mobility:
  region: Metro Manila
  mixing:
    school:
      append: false
      times:
        - 2020-02-11
        - 2020-03-16
      values:
        - 1.
        - 0.
  microdistancing:
    behaviour:
      parameters:
        times:
        - 75  # copy default values
        - 314 # copy default values
        - 446 # 21/3
        - 447 # 22/3 GCQ+ starts
        values:
        - 0.
        - 1.
        - 1.0
        - 1.3
time:
  end: 485
