description: BASELINE
parent: apps/covid_19/phl_submodel_params.yml

population:
  region: Metro Manila

mobility:
  region: Metro Manila
  mixing:
    school:
      append: false
      times:
        - 2020-02-11
        - 2020-03-16
      values:
        - 1.
        - 0.
    other_locations:
      append: true
      times:
      - 453 # 28/3
      - 454 # ECQ starts 29/3
      - 460 # ECQ ends 4/4
      - 461 # back to 22 March from 5/4
      values:
      - 0.52
      - 0.2
      - 0.2
      - 0.52
    work:
      append: true
      times:
      - 453 # 28/3
      - 454 # ECQ starts 29/3
      - 460 # ECQ ends 4/4
      - 461 # back to 22 March from 5/4
      values:
      - 0.55
      - 0.2
      - 0.2
      - 0.55
  microdistancing:
    behaviour:
      parameters:
        times:
        - 446 # 21/3
        - 447 # 22/3 GCQ+ starts
        - 453 # 28/3 GCQ+ ends
        - 454 # ECQ starts 29/3
        - 460 # ECQ ends 4/4
        - 461 # 5/4
        values:
        - 1.0
        - 1.3
        - 1.3
        - 2.
        - 2.
        - 1.3
