name: Continuous Integration
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - uses: s-weigand/setup-conda@v1
    - name: Install dependencies
      run: |
        conda install git pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: pytest
