name: Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test_basic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install Pip package manager
        run: python -m pip install --upgrade pip
      - name: Install Python dependencies via Pip
        run: pip install -r requirements.txt
      - name: Decrypt Autumn secrets
        run: python -m autumn secrets read
        env:
          AUTUMN_PASSWORD: ${{ secrets.AUTUMN_PASSWORD }}
      - name: Test with pytest
        run: pytest --workers 2 -W ignore -vv -m "not run_models and not calibrate_models and not mixing_optimisation and not benchmark"
  test_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install pip
        run: python -m pip install --upgrade pip
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Decrypt secrets
        run: python -m autumn secrets read
        env:
          AUTUMN_PASSWORD: ${{ secrets.AUTUMN_PASSWORD }}
      - name: Test with pytest
        run: pytest --cov --workers 2 -W ignore -vv -m run_models
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  test_calibrations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install pip
        run: python -m pip install --upgrade pip
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Decrypt secrets
        run: python -m autumn secrets read
        env:
          AUTUMN_PASSWORD: ${{ secrets.AUTUMN_PASSWORD }}
      - name: Test with pytest
        run: pytest --workers 2 -W ignore -vv -m calibrate_models
  test_mixing_optimisation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install pip
        run: python -m pip install --upgrade pip
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Decrypt secrets
        run: python -m autumn secrets read
        env:
          AUTUMN_PASSWORD: ${{ secrets.AUTUMN_PASSWORD }}
      - name: Test with pytest
        run: pytest --workers 2 -W ignore -vv -m mixing_optimisation
