name: Documentation
on:
  push:
    branches:
      - master

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install pip
        run: python -m pip install --upgrade pip
      - name: Install general dependencies
        run: pip install -r requirements.txt
      - name: Install doc dependencies
        run: pip install -r docs/requirements.txt
      - name: Build Sphinx docs
        run: ./scripts/docs/build.sh
      - name: Install deployment dependencies
        run: pip install awscli
      - name: Deploy Sphinx docs
        run: ./scripts/docs/deploy.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
