name: Nightly Acceptance
on:
  schedule:
    - cron:  '30 17 * * *'
  workflow_dispatch:

jobs:
  test_nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install Pip package manager
        run: python -m pip install --upgrade pip
      - name: Install Python dependencies via Pip
        run: pip install -r requirements.txt
      - name: Decrypt Autumn secrets
        run: python -m autumn secrets read
        env:
          AUTUMN_PASSWORD: ${{ secrets.AUTUMN_PASSWORD }}
      - name: Test with pytest
        run: pytest -W ignore -vv -m nightly
