name: Windows Acceptance
on:
  schedule:
    - cron:  '30 17 * * *'
  workflow_dispatch:

jobs:
  test_basic:
    runs-on: windows-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install Pip package manager
        run: python -m pip install --upgrade pip
      - name: Install Python dependencies via Pip
        run: pip install -r requirements/requirements310.txt
      - name: Decrypt Autumn secrets
        run: python -m autumn secrets read
        env:
          AUTUMN_PASSWORD: ${{ secrets.AUTUMN_PASSWORD }}
      - name: Test with pytest
        env:
          NIGHTLY_TESTING: 1
        run: pytest --workers 2 -W ignore -vv -m "not nightly and not run_models and not calibrate_models and not mixing_optimisation and not benchmark"
  test_runs:
    runs-on: windows-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install pip
        run: python -m pip install --upgrade pip
      - name: Install Python dependencies
        run: pip install -r requirements/requirements310.txt
      - name: Decrypt secrets
        run: python -m autumn secrets read
        env:
          AUTUMN_PASSWORD: ${{ secrets.AUTUMN_PASSWORD }}
      - name: Test with pytest
        env:
          NIGHTLY_TESTING: 1
        run: pytest --workers 2 -W ignore -vv -m run_models
  test_calibrations:
    runs-on: windows-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install pip
        run: python -m pip install --upgrade pip
      - name: Install Python dependencies
        run: pip install -r requirements/requirements310.txt
      - name: Decrypt secrets
        run: python -m autumn secrets read
        env:
          AUTUMN_PASSWORD: ${{ secrets.AUTUMN_PASSWORD }}
      - name: Test with pytest
        env:
          NIGHTLY_TESTING: 1
        run: pytest --workers 2 -W ignore -vv -m calibrate_models
  test_mixing_optimisation:
    runs-on: windows-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install pip
        run: python -m pip install --upgrade pip
      - name: Install Python dependencies
        run: pip install -r requirements/requirements310.txt
      - name: Decrypt secrets
        run: python -m autumn secrets read
        env:
          AUTUMN_PASSWORD: ${{ secrets.AUTUMN_PASSWORD }}
      - name: Test with pytest
        env:
          NIGHTLY_TESTING: 1
        run: pytest --workers 2 -W ignore -vv -m mixing_optimisation
