description: BASELINE

mobility:
  microdistancing:
    behaviour:
      parameters:
        times:
          - 75 # copy default values
          - 314 # copy default values
          - 446 # 21/3
          - 447 # 22/3 GCQ+ starts
          - 453 # 28/3 GCQ+ ends
          - 454 # 29/3 ECQ starts
          - 486 # MECQ ends
          - 490 # back to pre-ECQ MHS
        values:
          - 0.
          - 1.
          - 1.0
          - 1.15
          - 1.15
          - 1.5
          - 1.5
          - 1.15
